version: '3'

vars:
  PROTO_DIR: proto
  GO_OUT_DIR: .
  MODULE: "github.com/gofsd/object-history-api"
  CURRENT_VERSION:
    sh: git tag -l --sort -version:refname | head -n 1 || echo "v0.0.0"
  NEXT_VERSION:
    sh: |
      current="{{.CURRENT_VERSION}}"
      major=$(echo $current | cut -d'.' -f1)
      minor=$(echo $current | cut -d'.' -f2)
      patch=$(echo $current | cut -d'.' -f3)
      next_patch=$((patch + 1))
      echo "$major.$minor.$next_patch"

tasks:
  go:auth:
    desc: Generate auth Go gRPC code
    cmds:
      - |
        protoc \
          --proto_path={{.PROTO_DIR}} \
          --proto_path=third_party \
          --go_out={{.GO_OUT_DIR}} \
          --go-grpc_out={{.GO_OUT_DIR}} \
          {{.PROTO_DIR}}/auth/auth.proto

  go:object:
    desc: Generate object Go gRPC code
    cmds:
      - |
        protoc \
          --go_out={{.GO_OUT_DIR}} \
          --go-grpc_out={{.GO_OUT_DIR}} \
          {{.PROTO_DIR}}/object/object.proto

  go:cmd:
    desc: Generate command Go gRPC code
    cmds:
      - |
        protoc \
          --go_out={{.GO_OUT_DIR}} \
          --go-grpc_out={{.GO_OUT_DIR}} \
          {{.PROTO_DIR}}/cmd/cmd.proto

  go:all:
    desc: Generate go code for auth and object services 
    cmds:
      - task: go:auth
      - task: go:object
      - task: go:cmd


  java:auth:
    desc: "java"
    cmds:
      - |
        protoc \
          --proto_path={{.PROTO_DIR}} \
          --proto_path=third_party \
          --proto_path=./proto/auth/ \
          --java_out=java \
          --grpc-java_out=java \
          {{.PROTO_DIR}}/auth/auth.proto

  java:object:
    desc: "java"
    cmds:
      - |
        protoc \
          --proto_path=./proto/object/ \
          --java_out=java  \
          --grpc-java_out=java \
          {{.PROTO_DIR}}/object/object.proto

  java:cmd:
    desc: "java"
    cmds:
      - |
        protoc \
          --proto_path=./proto/cmd/ \
          --java_out=java  \
          --grpc-java_out=java \
          {{.PROTO_DIR}}/cmd/cmd.proto

  java:all:
    desc: Generate java code for auth and object services 
    cmds:
      - task: java:auth
      - task: java:object
      - task: java:cmd
  
  all:
    desc: Generate all languages and services
    cmds:
      - task: go:all
      - task: java:all

  patch:
    desc: "Patch Go module version and push to GitHub"
    cmds:
      - task all
      - "echo \"Current version: {{.CURRENT_VERSION}}\""
      - "echo \"Next version: v{{.NEXT_VERSION}}\""
      - git tag {{.NEXT_VERSION}}
      - git push origin {{.NEXT_VERSION}}
