// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package cmd;

public interface AddCommandToGroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmd.AddCommandToGroupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 command_id = 1;</code>
   * @return The commandId.
   */
  long getCommandId();

  /**
   * <code>uint64 group_id = 2;</code>
   * @return The groupId.
   */
  long getGroupId();
}
