// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package cmd;

public final class Cmd {
  private Cmd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Group_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_Group_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_GroupsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_GroupsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_GroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_GroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_UserGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_UserGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_ParameterField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_ParameterField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_Command_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_AddCommandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_AddCommandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CommandsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_CommandsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_DeleteCommandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_DeleteCommandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_ExecuteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_ExecuteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_ExecuteRequest_OverrideParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_ExecuteRequest_OverrideParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_ExecuteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_ExecuteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CancelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_CancelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CancelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_CancelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_RetryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_RetryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_DryRunResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_DryRunResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CommandLog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_CommandLog_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CommandLog_EffectiveParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_CommandLog_EffectiveParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_UpdateExecutionStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_UpdateExecutionStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_UpdateExecutionStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_UpdateExecutionStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_SubscribeCommandEventsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_SubscribeCommandEventsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CommandEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_CommandEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CommandEvent_EffectiveParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_CommandEvent_EffectiveParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Object_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_Object_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Object_FieldsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_Object_FieldsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_UserGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_UserGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Contact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_Contact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cmd_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tcmd.proto\022\003cmd\"<\n\005Group\022\020\n\010group_id\030\001 " +
      "\001(\004\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\"," +
      "\n\016GroupsResponse\022\032\n\006groups\030\001 \003(\0132\n.cmd.G" +
      "roup\" \n\014GroupRequest\022\020\n\010group_id\030\001 \001(\004\"R" +
      "\n\020UserGroupRequest\022\017\n\007user_id\030\001 \001(\004\022\020\n\010g" +
      "roup_id\030\002 \001(\004\022\033\n\004role\030\003 \001(\0162\r.cmd.UserRo" +
      "le\"\235\001\n\016ParameterField\022\014\n\004name\030\001 \001(\t\022\r\n\005l" +
      "abel\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\025\n\rdefault_valu" +
      "e\030\004 \001(\t\022\023\n\013description\030\005 \001(\t\022\017\n\007options\030" +
      "\006 \003(\t\022\020\n\010required\030\007 \001(\010\022\021\n\tmultiline\030\010 \001" +
      "(\010\"]\n\007Command\022\n\n\002id\030\001 \001(\004\022\014\n\004name\030\002 \001(\t\022" +
      "\023\n\013description\030\003 \001(\t\022#\n\006fields\030\004 \003(\0132\023.c" +
      "md.ParameterField\"[\n\021AddCommandRequest\022\014" +
      "\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022#\n\006fie" +
      "lds\030\003 \003(\0132\023.cmd.ParameterField\"2\n\020Comman" +
      "dsResponse\022\036\n\010commands\030\001 \003(\0132\014.cmd.Comma" +
      "nd\"\"\n\024DeleteCommandRequest\022\n\n\002id\030\001 \001(\004\"\251" +
      "\001\n\016ExecuteRequest\022\022\n\ncommand_id\030\001 \001(\004\022H\n" +
      "\023override_parameters\030\002 \003(\0132+.cmd.Execute" +
      "Request.OverrideParametersEntry\0329\n\027Overr" +
      "ideParametersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001\"S\n\017ExecuteResponse\022\024\n\014executi" +
      "on_id\030\001 \001(\004\022*\n\014queue_status\030\002 \001(\0162\024.cmd." +
      "ExecutionStatus\"%\n\rCancelRequest\022\024\n\014exec" +
      "ution_id\030\001 \001(\004\"!\n\016CancelResponse\022\017\n\007succ" +
      "ess\030\001 \001(\010\"$\n\014RetryRequest\022\024\n\014execution_i" +
      "d\030\001 \001(\004\"\"\n\014DryRunResult\022\022\n\ncommand_id\030\001 " +
      "\001(\004\"\022\n\020SubscribeRequest\"\230\002\n\nCommandLog\022\024" +
      "\n\014execution_id\030\001 \001(\004\022\022\n\ncommand_id\030\002 \001(\004" +
      "\022\016\n\006output\030\003 \001(\t\022$\n\006status\030\004 \001(\0162\024.cmd.E" +
      "xecutionStatus\022\021\n\ttimestamp\030\005 \001(\004\022F\n\024eff" +
      "ective_parameters\030\006 \003(\0132(.cmd.CommandLog" +
      ".EffectiveParametersEntry\022\023\n\013result_code" +
      "\030\007 \001(\t\032:\n\030EffectiveParametersEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\177\n\034UpdateExec" +
      "utionStatusRequest\022\024\n\014execution_id\030\001 \001(\004" +
      "\022$\n\006status\030\002 \001(\0162\024.cmd.ExecutionStatus\022\023" +
      "\n\013result_code\030\003 \001(\t\022\016\n\006output\030\004 \001(\t\"0\n\035U" +
      "pdateExecutionStatusResponse\022\017\n\007success\030" +
      "\001 \001(\010\"\037\n\035SubscribeCommandEventsRequest\"\321" +
      "\001\n\014CommandEvent\022\024\n\014execution_id\030\001 \001(\004\022\022\n" +
      "\ncommand_id\030\002 \001(\004\022H\n\024effective_parameter" +
      "s\030\003 \003(\0132*.cmd.CommandEvent.EffectivePara" +
      "metersEntry\022\021\n\ttimestamp\030\004 \001(\004\032:\n\030Effect" +
      "iveParametersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001\"l\n\006Object\022\n\n\002id\030\001 \001(\004\022\'\n\006fiel" +
      "ds\030\002 \003(\0132\027.cmd.Object.FieldsEntry\032-\n\013Fie" +
      "ldsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001" +
      "\"d\n\021UserGroupResponse\022\017\n\007user_id\030\001 \001(\004\022\020" +
      "\n\010group_id\030\002 \001(\004\022\033\n\004role\030\003 \001(\0162\r.cmd.Use" +
      "rRole\022\017\n\007message\030\004 \001(\t\"$\n\007Contact\022\n\n\002id\030" +
      "\001 \001(\004\022\r\n\005email\030\002 \001(\t\"\007\n\005Empty*\277\002\n\017Execut" +
      "ionStatus\022\034\n\030EXECUTION_STATUS_UNKNOWN\020\000\022" +
      "\034\n\030EXECUTION_STATUS_PENDING\020\001\022\034\n\030EXECUTI" +
      "ON_STATUS_RUNNING\020\002\022\034\n\030EXECUTION_STATUS_" +
      "SUCCESS\020\003\022\033\n\027EXECUTION_STATUS_FAILED\020\004\022\036" +
      "\n\032EXECUTION_STATUS_CANCELLED\020\005\022)\n%EXECUT" +
      "ION_STATUS_CANCELLED_BY_TIMEOUT\020\006\022\"\n\036EXE" +
      "CUTION_STATUS_NOT_PERMITTED\020\007\022(\n$EXECUTI" +
      "ON_STATUS_EXECUTORS_NOT_FOUND\020\010*M\n\010UserR" +
      "ole\022\024\n\020USER_ROLE_VIEWER\020\000\022\026\n\022USER_ROLE_E" +
      "XECUTOR\020\001\022\023\n\017USER_ROLE_ADMIN\020\0022\366\t\n\016Comma" +
      "ndService\022-\n\nListGroups\022\n.cmd.Empty\032\023.cm" +
      "d.GroupsResponse\022\"\n\010AddGroup\022\n.cmd.Group" +
      "\032\n.cmd.Group\022,\n\013DeleteGroup\022\021.cmd.GroupR" +
      "equest\032\n.cmd.Group\022?\n\016AddUserToGroup\022\025.c" +
      "md.UserGroupRequest\032\026.cmd.UserGroupRespo" +
      "nse\022D\n\023RemoveUserFromGroup\022\025.cmd.UserGro" +
      "upRequest\032\026.cmd.UserGroupResponse\0221\n\014Lis" +
      "tCommands\022\n.cmd.Empty\032\025.cmd.CommandsResp" +
      "onse\0222\n\nAddCommand\022\026.cmd.AddCommandReque" +
      "st\032\014.cmd.Command\0228\n\rDeleteCommand\022\031.cmd." +
      "DeleteCommandRequest\032\014.cmd.Command\022B\n\021Ad" +
      "dCommandToGroup\022\025.cmd.UserGroupRequest\032\026" +
      ".cmd.UserGroupResponse\022G\n\026DeleteCommandF" +
      "romGroup\022\025.cmd.UserGroupRequest\032\026.cmd.Us" +
      "erGroupResponse\022/\n\016ListExecutions\022\n.cmd." +
      "Empty\032\017.cmd.CommandLog0\001\0224\n\007Execute\022\023.cm" +
      "d.ExecuteRequest\032\024.cmd.ExecuteResponse\0221" +
      "\n\006Cancel\022\022.cmd.CancelRequest\032\023.cmd.Cance" +
      "lResponse\0220\n\005Retry\022\021.cmd.RetryRequest\032\024." +
      "cmd.ExecuteResponse\0220\n\006DryRun\022\023.cmd.Exec" +
      "uteRequest\032\021.cmd.DryRunResult\022^\n\025UpdateE" +
      "xecutionStatus\022!.cmd.UpdateExecutionStat" +
      "usRequest\032\".cmd.UpdateExecutionStatusRes" +
      "ponse\0229\n\rSubscribeLogs\022\025.cmd.SubscribeRe" +
      "quest\032\017.cmd.CommandLog0\001\0224\n\021ListCommandE" +
      "vents\022\n.cmd.Empty\032\021.cmd.CommandEvent0\001\022Q" +
      "\n\026SubscribeCommandEvents\022\".cmd.Subscribe" +
      "CommandEventsRequest\032\021.cmd.CommandEvent0" +
      "\001\022.\n\020AddMutualContact\022\014.cmd.Contact\032\014.cm" +
      "d.Contact\0221\n\023RemoveMutualContact\022\014.cmd.C" +
      "ontact\032\014.cmd.Contact\022)\n\rShowMyContact\022\n." +
      "cmd.Empty\032\014.cmd.ContactB\035\n\003cmdB\003CmdP\001Z\tc" +
      "md/proto\242\002\003CMDb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cmd_Group_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cmd_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_Group_descriptor,
        new java.lang.String[] { "GroupId", "Name", "Description", });
    internal_static_cmd_GroupsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cmd_GroupsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_GroupsResponse_descriptor,
        new java.lang.String[] { "Groups", });
    internal_static_cmd_GroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cmd_GroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_GroupRequest_descriptor,
        new java.lang.String[] { "GroupId", });
    internal_static_cmd_UserGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cmd_UserGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_UserGroupRequest_descriptor,
        new java.lang.String[] { "UserId", "GroupId", "Role", });
    internal_static_cmd_ParameterField_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cmd_ParameterField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_ParameterField_descriptor,
        new java.lang.String[] { "Name", "Label", "Type", "DefaultValue", "Description", "Options", "Required", "Multiline", });
    internal_static_cmd_Command_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cmd_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_Command_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Fields", });
    internal_static_cmd_AddCommandRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_cmd_AddCommandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_AddCommandRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "Fields", });
    internal_static_cmd_CommandsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_cmd_CommandsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_CommandsResponse_descriptor,
        new java.lang.String[] { "Commands", });
    internal_static_cmd_DeleteCommandRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_cmd_DeleteCommandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_DeleteCommandRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_cmd_ExecuteRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_cmd_ExecuteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_ExecuteRequest_descriptor,
        new java.lang.String[] { "CommandId", "OverrideParameters", });
    internal_static_cmd_ExecuteRequest_OverrideParametersEntry_descriptor =
      internal_static_cmd_ExecuteRequest_descriptor.getNestedTypes().get(0);
    internal_static_cmd_ExecuteRequest_OverrideParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_ExecuteRequest_OverrideParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_cmd_ExecuteResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_cmd_ExecuteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_ExecuteResponse_descriptor,
        new java.lang.String[] { "ExecutionId", "QueueStatus", });
    internal_static_cmd_CancelRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_cmd_CancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_CancelRequest_descriptor,
        new java.lang.String[] { "ExecutionId", });
    internal_static_cmd_CancelResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_cmd_CancelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_CancelResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_cmd_RetryRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_cmd_RetryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_RetryRequest_descriptor,
        new java.lang.String[] { "ExecutionId", });
    internal_static_cmd_DryRunResult_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_cmd_DryRunResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_DryRunResult_descriptor,
        new java.lang.String[] { "CommandId", });
    internal_static_cmd_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_cmd_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_SubscribeRequest_descriptor,
        new java.lang.String[] { });
    internal_static_cmd_CommandLog_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_cmd_CommandLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_CommandLog_descriptor,
        new java.lang.String[] { "ExecutionId", "CommandId", "Output", "Status", "Timestamp", "EffectiveParameters", "ResultCode", });
    internal_static_cmd_CommandLog_EffectiveParametersEntry_descriptor =
      internal_static_cmd_CommandLog_descriptor.getNestedTypes().get(0);
    internal_static_cmd_CommandLog_EffectiveParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_CommandLog_EffectiveParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_cmd_UpdateExecutionStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_cmd_UpdateExecutionStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_UpdateExecutionStatusRequest_descriptor,
        new java.lang.String[] { "ExecutionId", "Status", "ResultCode", "Output", });
    internal_static_cmd_UpdateExecutionStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_cmd_UpdateExecutionStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_UpdateExecutionStatusResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_cmd_SubscribeCommandEventsRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_cmd_SubscribeCommandEventsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_SubscribeCommandEventsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_cmd_CommandEvent_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_cmd_CommandEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_CommandEvent_descriptor,
        new java.lang.String[] { "ExecutionId", "CommandId", "EffectiveParameters", "Timestamp", });
    internal_static_cmd_CommandEvent_EffectiveParametersEntry_descriptor =
      internal_static_cmd_CommandEvent_descriptor.getNestedTypes().get(0);
    internal_static_cmd_CommandEvent_EffectiveParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_CommandEvent_EffectiveParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_cmd_Object_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_cmd_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_Object_descriptor,
        new java.lang.String[] { "Id", "Fields", });
    internal_static_cmd_Object_FieldsEntry_descriptor =
      internal_static_cmd_Object_descriptor.getNestedTypes().get(0);
    internal_static_cmd_Object_FieldsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_Object_FieldsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_cmd_UserGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_cmd_UserGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_UserGroupResponse_descriptor,
        new java.lang.String[] { "UserId", "GroupId", "Role", "Message", });
    internal_static_cmd_Contact_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_cmd_Contact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_Contact_descriptor,
        new java.lang.String[] { "Id", "Email", });
    internal_static_cmd_Empty_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_cmd_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cmd_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
