// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cmd/cmd.proto
// Protobuf Java Version: 4.28.2

package cmd;

public final class Cmd {
  private Cmd() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Cmd.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Group_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_Group_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_GroupsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_GroupsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_GroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_GroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_UserGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_UserGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_AddCommandToGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_AddCommandToGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_AddObjectsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_AddObjectsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_ParameterField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_ParameterField_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_Command_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_AddCommandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_AddCommandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CommandsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_CommandsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CommandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_CommandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_ExecuteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_ExecuteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_ExecuteRequest_OverrideParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_ExecuteRequest_OverrideParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_ExecuteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_ExecuteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CancelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_CancelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CancelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_CancelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_RetryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_RetryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_DryRunResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_DryRunResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CommandLog_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_CommandLog_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_UpdateExecutionStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_UpdateExecutionStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_UpdateExecutionStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_UpdateExecutionStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CommandEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_CommandEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_CommandEvent_EffectiveParametersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_CommandEvent_EffectiveParametersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Object_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_Object_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Object_FieldsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_Object_FieldsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_UserGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_UserGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Contact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_Contact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cmd_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cmd_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcmd/cmd.proto\022\003cmd\"<\n\005Group\022\020\n\010group_i" +
      "d\030\001 \001(\004\022\014\n\004name\030\002 \001(\t\022\023\n\013description\030\003 \001" +
      "(\t\",\n\016GroupsResponse\022\032\n\006groups\030\001 \003(\0132\n.c" +
      "md.Group\" \n\014GroupRequest\022\020\n\010group_id\030\001 \001" +
      "(\004\"R\n\020UserGroupRequest\022\017\n\007user_id\030\001 \001(\004\022" +
      "\020\n\010group_id\030\002 \001(\004\022\033\n\004role\030\003 \001(\0162\r.cmd.Us" +
      "erRole\"@\n\030AddCommandToGroupRequest\022\022\n\nco" +
      "mmand_id\030\001 \001(\004\022\020\n\010group_id\030\002 \001(\004\"9\n\021AddO" +
      "bjectsRequest\022\022\n\nobject_ids\030\001 \003(\004\022\020\n\010gro" +
      "up_id\030\002 \001(\004\"\304\001\n\016ParameterField\022\014\n\004name\030\001" +
      " \001(\t\022\r\n\005label\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\025\n\rdef" +
      "ault_value\030\004 \001(\t\022\023\n\013description\030\005 \001(\t\022\017\n" +
      "\007options\030\006 \003(\t\022\020\n\010required\030\007 \001(\010\022\021\n\tmult" +
      "iline\030\010 \001(\010\022\020\n\010disabled\030\t \001(\010\022\023\n\013placeho" +
      "lder\030\n \001(\t\"]\n\007Command\022\n\n\002id\030\001 \001(\004\022\014\n\004nam" +
      "e\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022#\n\006fields\030\004" +
      " \003(\0132\023.cmd.ParameterField\"j\n\021AddCommandR" +
      "equest\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 \001(" +
      "\t\022\r\n\005label\030\003 \001(\t\022#\n\006fields\030\004 \003(\0132\023.cmd.P" +
      "arameterField\"D\n\020CommandsResponse\022\020\n\010own" +
      "er_id\030\001 \001(\004\022\036\n\010commands\030\002 \003(\0132\014.cmd.Comm" +
      "and\"\034\n\016CommandRequest\022\n\n\002id\030\001 \001(\004\"\251\001\n\016Ex" +
      "ecuteRequest\022\022\n\ncommand_id\030\001 \001(\004\022H\n\023over" +
      "ride_parameters\030\002 \003(\0132+.cmd.ExecuteReque" +
      "st.OverrideParametersEntry\0329\n\027OverridePa" +
      "rametersEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\t:\0028\001\"S\n\017ExecuteResponse\022\024\n\014execution_id" +
      "\030\001 \001(\004\022*\n\014queue_status\030\002 \001(\0162\024.cmd.Execu" +
      "tionStatus\"%\n\rCancelRequest\022\024\n\014execution" +
      "_id\030\001 \001(\004\"!\n\016CancelResponse\022\017\n\007success\030\001" +
      " \001(\010\"$\n\014RetryRequest\022\024\n\014execution_id\030\001 \001" +
      "(\004\"\"\n\014DryRunResult\022\022\n\ncommand_id\030\001 \001(\004\"3" +
      "\n\020SubscribeRequest\022\014\n\004page\030\001 \001(\004\022\021\n\tpage" +
      "_size\030\002 \001(\004\"p\n\nCommandLog\022\024\n\014execution_i" +
      "d\030\001 \001(\004\022\016\n\006output\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001" +
      "(\004\022)\n\013result_code\030\004 \001(\0162\024.cmd.ExecutionS" +
      "tatus\"Z\n\034UpdateExecutionStatusRequest\022\024\n" +
      "\014execution_id\030\001 \001(\004\022$\n\006status\030\002 \001(\0162\024.cm" +
      "d.ExecutionStatus\"0\n\035UpdateExecutionStat" +
      "usResponse\022\017\n\007success\030\001 \001(\010\"\275\001\n\014CommandE" +
      "vent\022\024\n\014execution_id\030\001 \001(\004\022H\n\024effective_" +
      "parameters\030\002 \003(\0132*.cmd.CommandEvent.Effe" +
      "ctiveParametersEntry\022\021\n\ttimestamp\030\003 \001(\004\032" +
      ":\n\030EffectiveParametersEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t:\0028\001\"l\n\006Object\022\n\n\002id\030\001 \001(" +
      "\004\022\'\n\006fields\030\002 \003(\0132\027.cmd.Object.FieldsEnt" +
      "ry\032-\n\013FieldsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001\"d\n\021UserGroupResponse\022\017\n\007user_i" +
      "d\030\001 \001(\004\022\020\n\010group_id\030\002 \001(\004\022\033\n\004role\030\003 \001(\0162" +
      "\r.cmd.UserRole\022\017\n\007message\030\004 \001(\t\"$\n\007Conta" +
      "ct\022\n\n\002id\030\001 \001(\004\022\r\n\005email\030\002 \001(\t\"\007\n\005Empty*\277" +
      "\002\n\017ExecutionStatus\022\034\n\030EXECUTION_STATUS_U" +
      "NKNOWN\020\000\022\034\n\030EXECUTION_STATUS_PENDING\020\001\022\034" +
      "\n\030EXECUTION_STATUS_RUNNING\020\002\022\034\n\030EXECUTIO" +
      "N_STATUS_SUCCESS\020\003\022\033\n\027EXECUTION_STATUS_F" +
      "AILED\020\004\022\036\n\032EXECUTION_STATUS_CANCELLED\020\005\022" +
      ")\n%EXECUTION_STATUS_CANCELLED_BY_TIMEOUT" +
      "\020\006\022\"\n\036EXECUTION_STATUS_NOT_PERMITTED\020\007\022(" +
      "\n$EXECUTION_STATUS_EXECUTORS_NOT_FOUND\020\010" +
      "*M\n\010UserRole\022\024\n\020USER_ROLE_VIEWER\020\000\022\026\n\022US" +
      "ER_ROLE_EXECUTOR\020\001\022\023\n\017USER_ROLE_ADMIN\020\0022" +
      "\320\t\n\016CommandService\022-\n\nListGroups\022\n.cmd.E" +
      "mpty\032\023.cmd.GroupsResponse\022\"\n\010AddGroup\022\n." +
      "cmd.Group\032\n.cmd.Group\022,\n\013DeleteGroup\022\021.c" +
      "md.GroupRequest\032\n.cmd.Group\022?\n\016AddUserTo" +
      "Group\022\025.cmd.UserGroupRequest\032\026.cmd.UserG" +
      "roupResponse\022D\n\023RemoveUserFromGroup\022\025.cm" +
      "d.UserGroupRequest\032\026.cmd.UserGroupRespon" +
      "se\022:\n\014ListCommands\022\023.cmd.CommandRequest\032" +
      "\025.cmd.CommandsResponse\0222\n\nAddCommand\022\026.c" +
      "md.AddCommandRequest\032\014.cmd.Command\0222\n\rDe" +
      "leteCommand\022\023.cmd.CommandRequest\032\014.cmd.C" +
      "ommand\022J\n\021AddCommandToGroup\022\035.cmd.AddCom" +
      "mandToGroupRequest\032\026.cmd.UserGroupRespon" +
      "se\022G\n\026DeleteCommandFromGroup\022\025.cmd.UserG" +
      "roupRequest\032\026.cmd.UserGroupResponse\022C\n\021A" +
      "ddObjectsToGroup\022\026.cmd.AddObjectsRequest" +
      "\032\026.cmd.UserGroupResponse\0224\n\007Execute\022\023.cm" +
      "d.ExecuteRequest\032\024.cmd.ExecuteResponse\0221" +
      "\n\006Cancel\022\022.cmd.CancelRequest\032\023.cmd.Cance" +
      "lResponse\0220\n\005Retry\022\021.cmd.RetryRequest\032\024." +
      "cmd.ExecuteResponse\0220\n\006DryRun\022\023.cmd.Exec" +
      "uteRequest\032\021.cmd.DryRunResult\022^\n\025UpdateE" +
      "xecutionStatus\022!.cmd.UpdateExecutionStat" +
      "usRequest\032\".cmd.UpdateExecutionStatusRes" +
      "ponse\022;\n\rSubscribeLogs\022\025.cmd.SubscribeRe" +
      "quest\032\017.cmd.CommandLog(\0010\001\022@\n\026SubscribeC" +
      "ommandEvents\022\017.cmd.CommandLog\032\021.cmd.Comm" +
      "andEvent(\0010\001\022.\n\020AddMutualContact\022\014.cmd.C" +
      "ontact\032\014.cmd.Contact\0221\n\023RemoveMutualCont" +
      "act\022\014.cmd.Contact\032\014.cmd.Contact\022)\n\rShowM" +
      "yContact\022\n.cmd.Empty\032\014.cmd.ContactB\035\n\003cm" +
      "dB\003CmdP\001Z\tcmd/proto\242\002\003CMDb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cmd_Group_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cmd_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_Group_descriptor,
        new java.lang.String[] { "GroupId", "Name", "Description", });
    internal_static_cmd_GroupsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cmd_GroupsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_GroupsResponse_descriptor,
        new java.lang.String[] { "Groups", });
    internal_static_cmd_GroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cmd_GroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_GroupRequest_descriptor,
        new java.lang.String[] { "GroupId", });
    internal_static_cmd_UserGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cmd_UserGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_UserGroupRequest_descriptor,
        new java.lang.String[] { "UserId", "GroupId", "Role", });
    internal_static_cmd_AddCommandToGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_cmd_AddCommandToGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_AddCommandToGroupRequest_descriptor,
        new java.lang.String[] { "CommandId", "GroupId", });
    internal_static_cmd_AddObjectsRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_cmd_AddObjectsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_AddObjectsRequest_descriptor,
        new java.lang.String[] { "ObjectIds", "GroupId", });
    internal_static_cmd_ParameterField_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_cmd_ParameterField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_ParameterField_descriptor,
        new java.lang.String[] { "Name", "Label", "Type", "DefaultValue", "Description", "Options", "Required", "Multiline", "Disabled", "Placeholder", });
    internal_static_cmd_Command_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_cmd_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_Command_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Fields", });
    internal_static_cmd_AddCommandRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_cmd_AddCommandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_AddCommandRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "Label", "Fields", });
    internal_static_cmd_CommandsResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_cmd_CommandsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_CommandsResponse_descriptor,
        new java.lang.String[] { "OwnerId", "Commands", });
    internal_static_cmd_CommandRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_cmd_CommandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_CommandRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_cmd_ExecuteRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_cmd_ExecuteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_ExecuteRequest_descriptor,
        new java.lang.String[] { "CommandId", "OverrideParameters", });
    internal_static_cmd_ExecuteRequest_OverrideParametersEntry_descriptor =
      internal_static_cmd_ExecuteRequest_descriptor.getNestedTypes().get(0);
    internal_static_cmd_ExecuteRequest_OverrideParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_ExecuteRequest_OverrideParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_cmd_ExecuteResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_cmd_ExecuteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_ExecuteResponse_descriptor,
        new java.lang.String[] { "ExecutionId", "QueueStatus", });
    internal_static_cmd_CancelRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_cmd_CancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_CancelRequest_descriptor,
        new java.lang.String[] { "ExecutionId", });
    internal_static_cmd_CancelResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_cmd_CancelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_CancelResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_cmd_RetryRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_cmd_RetryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_RetryRequest_descriptor,
        new java.lang.String[] { "ExecutionId", });
    internal_static_cmd_DryRunResult_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_cmd_DryRunResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_DryRunResult_descriptor,
        new java.lang.String[] { "CommandId", });
    internal_static_cmd_SubscribeRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_cmd_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_SubscribeRequest_descriptor,
        new java.lang.String[] { "Page", "PageSize", });
    internal_static_cmd_CommandLog_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_cmd_CommandLog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_CommandLog_descriptor,
        new java.lang.String[] { "ExecutionId", "Output", "Timestamp", "ResultCode", });
    internal_static_cmd_UpdateExecutionStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_cmd_UpdateExecutionStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_UpdateExecutionStatusRequest_descriptor,
        new java.lang.String[] { "ExecutionId", "Status", });
    internal_static_cmd_UpdateExecutionStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_cmd_UpdateExecutionStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_UpdateExecutionStatusResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_cmd_CommandEvent_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_cmd_CommandEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_CommandEvent_descriptor,
        new java.lang.String[] { "ExecutionId", "EffectiveParameters", "Timestamp", });
    internal_static_cmd_CommandEvent_EffectiveParametersEntry_descriptor =
      internal_static_cmd_CommandEvent_descriptor.getNestedTypes().get(0);
    internal_static_cmd_CommandEvent_EffectiveParametersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_CommandEvent_EffectiveParametersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_cmd_Object_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_cmd_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_Object_descriptor,
        new java.lang.String[] { "Id", "Fields", });
    internal_static_cmd_Object_FieldsEntry_descriptor =
      internal_static_cmd_Object_descriptor.getNestedTypes().get(0);
    internal_static_cmd_Object_FieldsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_Object_FieldsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_cmd_UserGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_cmd_UserGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_UserGroupResponse_descriptor,
        new java.lang.String[] { "UserId", "GroupId", "Role", "Message", });
    internal_static_cmd_Contact_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_cmd_Contact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_Contact_descriptor,
        new java.lang.String[] { "Id", "Email", });
    internal_static_cmd_Empty_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_cmd_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cmd_Empty_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
