// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cmd/cmd.proto
// Protobuf Java Version: 4.28.2

package cmd;

/**
 * <pre>
 * CommandsResponse is a wrapper for a list of commands.
 * </pre>
 *
 * Protobuf type {@code cmd.CommandsResponse}
 */
public final class CommandsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:cmd.CommandsResponse)
    CommandsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      CommandsResponse.class.getName());
  }
  // Use CommandsResponse.newBuilder() to construct.
  private CommandsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CommandsResponse() {
    commands_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cmd.Cmd.internal_static_cmd_CommandsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cmd.Cmd.internal_static_cmd_CommandsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cmd.CommandsResponse.class, cmd.CommandsResponse.Builder.class);
  }

  public static final int OWNER_ID_FIELD_NUMBER = 1;
  private long ownerId_ = 0L;
  /**
   * <pre>
   * ID of the owner of the commands
   * </pre>
   *
   * <code>uint64 owner_id = 1;</code>
   * @return The ownerId.
   */
  @java.lang.Override
  public long getOwnerId() {
    return ownerId_;
  }

  public static final int COMMANDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<cmd.Command> commands_;
  /**
   * <code>repeated .cmd.Command commands = 2;</code>
   */
  @java.lang.Override
  public java.util.List<cmd.Command> getCommandsList() {
    return commands_;
  }
  /**
   * <code>repeated .cmd.Command commands = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cmd.CommandOrBuilder> 
      getCommandsOrBuilderList() {
    return commands_;
  }
  /**
   * <code>repeated .cmd.Command commands = 2;</code>
   */
  @java.lang.Override
  public int getCommandsCount() {
    return commands_.size();
  }
  /**
   * <code>repeated .cmd.Command commands = 2;</code>
   */
  @java.lang.Override
  public cmd.Command getCommands(int index) {
    return commands_.get(index);
  }
  /**
   * <code>repeated .cmd.Command commands = 2;</code>
   */
  @java.lang.Override
  public cmd.CommandOrBuilder getCommandsOrBuilder(
      int index) {
    return commands_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ownerId_ != 0L) {
      output.writeUInt64(1, ownerId_);
    }
    for (int i = 0; i < commands_.size(); i++) {
      output.writeMessage(2, commands_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ownerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, ownerId_);
    }
    for (int i = 0; i < commands_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, commands_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cmd.CommandsResponse)) {
      return super.equals(obj);
    }
    cmd.CommandsResponse other = (cmd.CommandsResponse) obj;

    if (getOwnerId()
        != other.getOwnerId()) return false;
    if (!getCommandsList()
        .equals(other.getCommandsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OWNER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOwnerId());
    if (getCommandsCount() > 0) {
      hash = (37 * hash) + COMMANDS_FIELD_NUMBER;
      hash = (53 * hash) + getCommandsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cmd.CommandsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cmd.CommandsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cmd.CommandsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cmd.CommandsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cmd.CommandsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cmd.CommandsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cmd.CommandsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cmd.CommandsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cmd.CommandsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cmd.CommandsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cmd.CommandsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cmd.CommandsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cmd.CommandsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * CommandsResponse is a wrapper for a list of commands.
   * </pre>
   *
   * Protobuf type {@code cmd.CommandsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cmd.CommandsResponse)
      cmd.CommandsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cmd.Cmd.internal_static_cmd_CommandsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cmd.Cmd.internal_static_cmd_CommandsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cmd.CommandsResponse.class, cmd.CommandsResponse.Builder.class);
    }

    // Construct using cmd.CommandsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ownerId_ = 0L;
      if (commandsBuilder_ == null) {
        commands_ = java.util.Collections.emptyList();
      } else {
        commands_ = null;
        commandsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cmd.Cmd.internal_static_cmd_CommandsResponse_descriptor;
    }

    @java.lang.Override
    public cmd.CommandsResponse getDefaultInstanceForType() {
      return cmd.CommandsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public cmd.CommandsResponse build() {
      cmd.CommandsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cmd.CommandsResponse buildPartial() {
      cmd.CommandsResponse result = new cmd.CommandsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cmd.CommandsResponse result) {
      if (commandsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          commands_ = java.util.Collections.unmodifiableList(commands_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.commands_ = commands_;
      } else {
        result.commands_ = commandsBuilder_.build();
      }
    }

    private void buildPartial0(cmd.CommandsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ownerId_ = ownerId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cmd.CommandsResponse) {
        return mergeFrom((cmd.CommandsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cmd.CommandsResponse other) {
      if (other == cmd.CommandsResponse.getDefaultInstance()) return this;
      if (other.getOwnerId() != 0L) {
        setOwnerId(other.getOwnerId());
      }
      if (commandsBuilder_ == null) {
        if (!other.commands_.isEmpty()) {
          if (commands_.isEmpty()) {
            commands_ = other.commands_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCommandsIsMutable();
            commands_.addAll(other.commands_);
          }
          onChanged();
        }
      } else {
        if (!other.commands_.isEmpty()) {
          if (commandsBuilder_.isEmpty()) {
            commandsBuilder_.dispose();
            commandsBuilder_ = null;
            commands_ = other.commands_;
            bitField0_ = (bitField0_ & ~0x00000002);
            commandsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getCommandsFieldBuilder() : null;
          } else {
            commandsBuilder_.addAllMessages(other.commands_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              ownerId_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              cmd.Command m =
                  input.readMessage(
                      cmd.Command.parser(),
                      extensionRegistry);
              if (commandsBuilder_ == null) {
                ensureCommandsIsMutable();
                commands_.add(m);
              } else {
                commandsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long ownerId_ ;
    /**
     * <pre>
     * ID of the owner of the commands
     * </pre>
     *
     * <code>uint64 owner_id = 1;</code>
     * @return The ownerId.
     */
    @java.lang.Override
    public long getOwnerId() {
      return ownerId_;
    }
    /**
     * <pre>
     * ID of the owner of the commands
     * </pre>
     *
     * <code>uint64 owner_id = 1;</code>
     * @param value The ownerId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerId(long value) {

      ownerId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the owner of the commands
     * </pre>
     *
     * <code>uint64 owner_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ownerId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<cmd.Command> commands_ =
      java.util.Collections.emptyList();
    private void ensureCommandsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        commands_ = new java.util.ArrayList<cmd.Command>(commands_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cmd.Command, cmd.Command.Builder, cmd.CommandOrBuilder> commandsBuilder_;

    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public java.util.List<cmd.Command> getCommandsList() {
      if (commandsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(commands_);
      } else {
        return commandsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public int getCommandsCount() {
      if (commandsBuilder_ == null) {
        return commands_.size();
      } else {
        return commandsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public cmd.Command getCommands(int index) {
      if (commandsBuilder_ == null) {
        return commands_.get(index);
      } else {
        return commandsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public Builder setCommands(
        int index, cmd.Command value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.set(index, value);
        onChanged();
      } else {
        commandsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public Builder setCommands(
        int index, cmd.Command.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.set(index, builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public Builder addCommands(cmd.Command value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.add(value);
        onChanged();
      } else {
        commandsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public Builder addCommands(
        int index, cmd.Command value) {
      if (commandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommandsIsMutable();
        commands_.add(index, value);
        onChanged();
      } else {
        commandsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public Builder addCommands(
        cmd.Command.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.add(builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public Builder addCommands(
        int index, cmd.Command.Builder builderForValue) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.add(index, builderForValue.build());
        onChanged();
      } else {
        commandsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public Builder addAllCommands(
        java.lang.Iterable<? extends cmd.Command> values) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, commands_);
        onChanged();
      } else {
        commandsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public Builder clearCommands() {
      if (commandsBuilder_ == null) {
        commands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        commandsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public Builder removeCommands(int index) {
      if (commandsBuilder_ == null) {
        ensureCommandsIsMutable();
        commands_.remove(index);
        onChanged();
      } else {
        commandsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public cmd.Command.Builder getCommandsBuilder(
        int index) {
      return getCommandsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public cmd.CommandOrBuilder getCommandsOrBuilder(
        int index) {
      if (commandsBuilder_ == null) {
        return commands_.get(index);  } else {
        return commandsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public java.util.List<? extends cmd.CommandOrBuilder> 
         getCommandsOrBuilderList() {
      if (commandsBuilder_ != null) {
        return commandsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(commands_);
      }
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public cmd.Command.Builder addCommandsBuilder() {
      return getCommandsFieldBuilder().addBuilder(
          cmd.Command.getDefaultInstance());
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public cmd.Command.Builder addCommandsBuilder(
        int index) {
      return getCommandsFieldBuilder().addBuilder(
          index, cmd.Command.getDefaultInstance());
    }
    /**
     * <code>repeated .cmd.Command commands = 2;</code>
     */
    public java.util.List<cmd.Command.Builder> 
         getCommandsBuilderList() {
      return getCommandsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cmd.Command, cmd.Command.Builder, cmd.CommandOrBuilder> 
        getCommandsFieldBuilder() {
      if (commandsBuilder_ == null) {
        commandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cmd.Command, cmd.Command.Builder, cmd.CommandOrBuilder>(
                commands_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        commands_ = null;
      }
      return commandsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:cmd.CommandsResponse)
  }

  // @@protoc_insertion_point(class_scope:cmd.CommandsResponse)
  private static final cmd.CommandsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cmd.CommandsResponse();
  }

  public static cmd.CommandsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommandsResponse>
      PARSER = new com.google.protobuf.AbstractParser<CommandsResponse>() {
    @java.lang.Override
    public CommandsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CommandsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommandsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cmd.CommandsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

