// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cmd.proto
// Protobuf Java Version: 4.28.2

package cmd;

public interface CommandLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmd.CommandLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 execution_id = 1;</code>
   * @return The executionId.
   */
  long getExecutionId();

  /**
   * <code>string output = 2;</code>
   * @return The output.
   */
  java.lang.String getOutput();
  /**
   * <code>string output = 2;</code>
   * @return The bytes for output.
   */
  com.google.protobuf.ByteString
      getOutputBytes();

  /**
   * <code>uint64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>.cmd.ExecutionStatus result_code = 4;</code>
   * @return The enum numeric value on the wire for resultCode.
   */
  int getResultCodeValue();
  /**
   * <code>.cmd.ExecutionStatus result_code = 4;</code>
   * @return The resultCode.
   */
  cmd.ExecutionStatus getResultCode();
}
