// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package cmd;

public interface CommandTemplateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:command.CommandTemplate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 command_template_id = 1;</code>
   * @return The commandTemplateId.
   */
  long getCommandTemplateId();

  /**
   * <code>int64 group_id = 2;</code>
   * @return The groupId.
   */
  long getGroupId();

  /**
   * <code>string command = 3;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 3;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>repeated .command.ParameterField fields = 4;</code>
   */
  java.util.List<cmd.ParameterField> 
      getFieldsList();
  /**
   * <code>repeated .command.ParameterField fields = 4;</code>
   */
  cmd.ParameterField getFields(int index);
  /**
   * <code>repeated .command.ParameterField fields = 4;</code>
   */
  int getFieldsCount();
  /**
   * <code>repeated .command.ParameterField fields = 4;</code>
   */
  java.util.List<? extends cmd.ParameterFieldOrBuilder> 
      getFieldsOrBuilderList();
  /**
   * <code>repeated .command.ParameterField fields = 4;</code>
   */
  cmd.ParameterFieldOrBuilder getFieldsOrBuilder(
      int index);

  /**
   * <code>repeated string sensitive_keys = 5;</code>
   * @return A list containing the sensitiveKeys.
   */
  java.util.List<java.lang.String>
      getSensitiveKeysList();
  /**
   * <code>repeated string sensitive_keys = 5;</code>
   * @return The count of sensitiveKeys.
   */
  int getSensitiveKeysCount();
  /**
   * <code>repeated string sensitive_keys = 5;</code>
   * @param index The index of the element to return.
   * @return The sensitiveKeys at the given index.
   */
  java.lang.String getSensitiveKeys(int index);
  /**
   * <code>repeated string sensitive_keys = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the sensitiveKeys at the given index.
   */
  com.google.protobuf.ByteString
      getSensitiveKeysBytes(int index);

  /**
   * <code>repeated string tags = 6;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <code>repeated string tags = 6;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <code>repeated string tags = 6;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <code>repeated string tags = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <code>string description = 7;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 7;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
