// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cmd/cmd.proto
// Protobuf Java Version: 4.33.0

package cmd;

@com.google.protobuf.Generated
public interface CommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmd.Command)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated .cmd.ParameterField fields = 4;</code>
   */
  java.util.List<cmd.ParameterField> 
      getFieldsList();
  /**
   * <code>repeated .cmd.ParameterField fields = 4;</code>
   */
  cmd.ParameterField getFields(int index);
  /**
   * <code>repeated .cmd.ParameterField fields = 4;</code>
   */
  int getFieldsCount();
  /**
   * <code>repeated .cmd.ParameterField fields = 4;</code>
   */
  java.util.List<? extends cmd.ParameterFieldOrBuilder> 
      getFieldsOrBuilderList();
  /**
   * <code>repeated .cmd.ParameterField fields = 4;</code>
   */
  cmd.ParameterFieldOrBuilder getFieldsOrBuilder(
      int index);

  /**
   * <code>string device = 5;</code>
   * @return The device.
   */
  java.lang.String getDevice();
  /**
   * <code>string device = 5;</code>
   * @return The bytes for device.
   */
  com.google.protobuf.ByteString
      getDeviceBytes();

  /**
   * <code>string label = 6;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 6;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>.cmd.CommandType type = 7;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.cmd.CommandType type = 7;</code>
   * @return The type.
   */
  cmd.CommandType getType();
}
