// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cmd/cmd.proto
// Protobuf Java Version: 4.32.1

package cmd;

@com.google.protobuf.Generated
public interface CommandRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmd.CommandRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
