// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package cmd;

public interface ContactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmd.Contact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The ID of the user to be added as a contact.
   * </pre>
   *
   * <code>uint64 contact_id = 2;</code>
   * @return The contactId.
   */
  long getContactId();
}
