// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cmd/cmd.proto
// Protobuf Java Version: 4.32.1

package cmd;

@com.google.protobuf.Generated
public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmd.Empty)
    com.google.protobuf.MessageOrBuilder {
}
