// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package cmd;

/**
 * Protobuf type {@code command.ExecuteResponse}
 */
public final class ExecuteResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:command.ExecuteResponse)
    ExecuteResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecuteResponse.newBuilder() to construct.
  private ExecuteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecuteResponse() {
    queueStatus_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExecuteResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cmd.Command.internal_static_command_ExecuteResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cmd.Command.internal_static_command_ExecuteResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cmd.ExecuteResponse.class, cmd.ExecuteResponse.Builder.class);
  }

  public static final int EXECUTION_ID_FIELD_NUMBER = 1;
  private long executionId_;
  /**
   * <code>int64 execution_id = 1;</code>
   * @return The executionId.
   */
  @java.lang.Override
  public long getExecutionId() {
    return executionId_;
  }

  public static final int QUEUE_STATUS_FIELD_NUMBER = 2;
  private int queueStatus_;
  /**
   * <code>.command.ExecutionStatus queue_status = 2;</code>
   * @return The enum numeric value on the wire for queueStatus.
   */
  @java.lang.Override public int getQueueStatusValue() {
    return queueStatus_;
  }
  /**
   * <code>.command.ExecutionStatus queue_status = 2;</code>
   * @return The queueStatus.
   */
  @java.lang.Override public cmd.ExecutionStatus getQueueStatus() {
    @SuppressWarnings("deprecation")
    cmd.ExecutionStatus result = cmd.ExecutionStatus.valueOf(queueStatus_);
    return result == null ? cmd.ExecutionStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (executionId_ != 0L) {
      output.writeInt64(1, executionId_);
    }
    if (queueStatus_ != cmd.ExecutionStatus.UNKNOWN.getNumber()) {
      output.writeEnum(2, queueStatus_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (executionId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, executionId_);
    }
    if (queueStatus_ != cmd.ExecutionStatus.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, queueStatus_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cmd.ExecuteResponse)) {
      return super.equals(obj);
    }
    cmd.ExecuteResponse other = (cmd.ExecuteResponse) obj;

    if (getExecutionId()
        != other.getExecutionId()) return false;
    if (queueStatus_ != other.queueStatus_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXECUTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExecutionId());
    hash = (37 * hash) + QUEUE_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + queueStatus_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cmd.ExecuteResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cmd.ExecuteResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cmd.ExecuteResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cmd.ExecuteResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cmd.ExecuteResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cmd.ExecuteResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cmd.ExecuteResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cmd.ExecuteResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cmd.ExecuteResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cmd.ExecuteResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cmd.ExecuteResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cmd.ExecuteResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cmd.ExecuteResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code command.ExecuteResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:command.ExecuteResponse)
      cmd.ExecuteResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cmd.Command.internal_static_command_ExecuteResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cmd.Command.internal_static_command_ExecuteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cmd.ExecuteResponse.class, cmd.ExecuteResponse.Builder.class);
    }

    // Construct using cmd.ExecuteResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      executionId_ = 0L;

      queueStatus_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cmd.Command.internal_static_command_ExecuteResponse_descriptor;
    }

    @java.lang.Override
    public cmd.ExecuteResponse getDefaultInstanceForType() {
      return cmd.ExecuteResponse.getDefaultInstance();
    }

    @java.lang.Override
    public cmd.ExecuteResponse build() {
      cmd.ExecuteResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cmd.ExecuteResponse buildPartial() {
      cmd.ExecuteResponse result = new cmd.ExecuteResponse(this);
      result.executionId_ = executionId_;
      result.queueStatus_ = queueStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cmd.ExecuteResponse) {
        return mergeFrom((cmd.ExecuteResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cmd.ExecuteResponse other) {
      if (other == cmd.ExecuteResponse.getDefaultInstance()) return this;
      if (other.getExecutionId() != 0L) {
        setExecutionId(other.getExecutionId());
      }
      if (other.queueStatus_ != 0) {
        setQueueStatusValue(other.getQueueStatusValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              executionId_ = input.readInt64();

              break;
            } // case 8
            case 16: {
              queueStatus_ = input.readEnum();

              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private long executionId_ ;
    /**
     * <code>int64 execution_id = 1;</code>
     * @return The executionId.
     */
    @java.lang.Override
    public long getExecutionId() {
      return executionId_;
    }
    /**
     * <code>int64 execution_id = 1;</code>
     * @param value The executionId to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionId(long value) {
      
      executionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 execution_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutionId() {
      
      executionId_ = 0L;
      onChanged();
      return this;
    }

    private int queueStatus_ = 0;
    /**
     * <code>.command.ExecutionStatus queue_status = 2;</code>
     * @return The enum numeric value on the wire for queueStatus.
     */
    @java.lang.Override public int getQueueStatusValue() {
      return queueStatus_;
    }
    /**
     * <code>.command.ExecutionStatus queue_status = 2;</code>
     * @param value The enum numeric value on the wire for queueStatus to set.
     * @return This builder for chaining.
     */
    public Builder setQueueStatusValue(int value) {
      
      queueStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.command.ExecutionStatus queue_status = 2;</code>
     * @return The queueStatus.
     */
    @java.lang.Override
    public cmd.ExecutionStatus getQueueStatus() {
      @SuppressWarnings("deprecation")
      cmd.ExecutionStatus result = cmd.ExecutionStatus.valueOf(queueStatus_);
      return result == null ? cmd.ExecutionStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.command.ExecutionStatus queue_status = 2;</code>
     * @param value The queueStatus to set.
     * @return This builder for chaining.
     */
    public Builder setQueueStatus(cmd.ExecutionStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      queueStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.command.ExecutionStatus queue_status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueueStatus() {
      
      queueStatus_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:command.ExecuteResponse)
  }

  // @@protoc_insertion_point(class_scope:command.ExecuteResponse)
  private static final cmd.ExecuteResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cmd.ExecuteResponse();
  }

  public static cmd.ExecuteResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecuteResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExecuteResponse>() {
    @java.lang.Override
    public ExecuteResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExecuteResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecuteResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cmd.ExecuteResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

