// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package cmd;

public interface ExecuteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:command.ExecuteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 execution_id = 1;</code>
   * @return The executionId.
   */
  long getExecutionId();

  /**
   * <code>.command.ExecutionStatus queue_status = 2;</code>
   * @return The enum numeric value on the wire for queueStatus.
   */
  int getQueueStatusValue();
  /**
   * <code>.command.ExecutionStatus queue_status = 2;</code>
   * @return The queueStatus.
   */
  cmd.ExecutionStatus getQueueStatus();
}
