// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package cmd;

public interface GroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmd.GroupRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 group_id = 1;</code>
   * @return The groupId.
   */
  long getGroupId();
}
