// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cmd/cmd.proto
// Protobuf Java Version: 4.28.2

package cmd;

public interface ParameterFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmd.ParameterField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string label = 2;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string default_value = 4;</code>
   * @return The defaultValue.
   */
  java.lang.String getDefaultValue();
  /**
   * <code>string default_value = 4;</code>
   * @return The bytes for defaultValue.
   */
  com.google.protobuf.ByteString
      getDefaultValueBytes();

  /**
   * <code>string description = 5;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 5;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>repeated string options = 6;</code>
   * @return A list containing the options.
   */
  java.util.List<java.lang.String>
      getOptionsList();
  /**
   * <code>repeated string options = 6;</code>
   * @return The count of options.
   */
  int getOptionsCount();
  /**
   * <code>repeated string options = 6;</code>
   * @param index The index of the element to return.
   * @return The options at the given index.
   */
  java.lang.String getOptions(int index);
  /**
   * <code>repeated string options = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the options at the given index.
   */
  com.google.protobuf.ByteString
      getOptionsBytes(int index);

  /**
   * <code>bool required = 7;</code>
   * @return The required.
   */
  boolean getRequired();

  /**
   * <code>bool multiline = 8;</code>
   * @return The multiline.
   */
  boolean getMultiline();

  /**
   * <pre>
   * Indicates if the field is disabled in the UI
   * </pre>
   *
   * <code>bool disabled = 9;</code>
   * @return The disabled.
   */
  boolean getDisabled();

  /**
   * <pre>
   * Placeholder text for the field
   * </pre>
   *
   * <code>string placeholder = 10;</code>
   * @return The placeholder.
   */
  java.lang.String getPlaceholder();
  /**
   * <pre>
   * Placeholder text for the field
   * </pre>
   *
   * <code>string placeholder = 10;</code>
   * @return The bytes for placeholder.
   */
  com.google.protobuf.ByteString
      getPlaceholderBytes();
}
