// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package cmd;

public interface RetryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:command.RetryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 execution_id = 1;</code>
   * @return The executionId.
   */
  long getExecutionId();

  /**
   * <code>int64 user_id = 2;</code>
   * @return The userId.
   */
  long getUserId();
}
