// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package cmd;

public interface RetryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmd.RetryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 execution_id = 1;</code>
   * @return The executionId.
   */
  long getExecutionId();
}
