// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmd.proto

package cmd;

/**
 * Protobuf type {@code command.SubscribeCommandEventsRequest}
 */
public final class SubscribeCommandEventsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:command.SubscribeCommandEventsRequest)
    SubscribeCommandEventsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubscribeCommandEventsRequest.newBuilder() to construct.
  private SubscribeCommandEventsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubscribeCommandEventsRequest() {
    groupIds_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubscribeCommandEventsRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cmd.Command.internal_static_command_SubscribeCommandEventsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cmd.Command.internal_static_command_SubscribeCommandEventsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cmd.SubscribeCommandEventsRequest.class, cmd.SubscribeCommandEventsRequest.Builder.class);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  private long userId_;
  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int GROUP_IDS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.LongList groupIds_;
  /**
   * <code>repeated int64 group_ids = 2;</code>
   * @return A list containing the groupIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getGroupIdsList() {
    return groupIds_;
  }
  /**
   * <code>repeated int64 group_ids = 2;</code>
   * @return The count of groupIds.
   */
  public int getGroupIdsCount() {
    return groupIds_.size();
  }
  /**
   * <code>repeated int64 group_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The groupIds at the given index.
   */
  public long getGroupIds(int index) {
    return groupIds_.getLong(index);
  }
  private int groupIdsMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (getGroupIdsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(groupIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < groupIds_.size(); i++) {
      output.writeInt64NoTag(groupIds_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < groupIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(groupIds_.getLong(i));
      }
      size += dataSize;
      if (!getGroupIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      groupIdsMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cmd.SubscribeCommandEventsRequest)) {
      return super.equals(obj);
    }
    cmd.SubscribeCommandEventsRequest other = (cmd.SubscribeCommandEventsRequest) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (!getGroupIdsList()
        .equals(other.getGroupIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    if (getGroupIdsCount() > 0) {
      hash = (37 * hash) + GROUP_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getGroupIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cmd.SubscribeCommandEventsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cmd.SubscribeCommandEventsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cmd.SubscribeCommandEventsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cmd.SubscribeCommandEventsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cmd.SubscribeCommandEventsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cmd.SubscribeCommandEventsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cmd.SubscribeCommandEventsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cmd.SubscribeCommandEventsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cmd.SubscribeCommandEventsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cmd.SubscribeCommandEventsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cmd.SubscribeCommandEventsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cmd.SubscribeCommandEventsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cmd.SubscribeCommandEventsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code command.SubscribeCommandEventsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:command.SubscribeCommandEventsRequest)
      cmd.SubscribeCommandEventsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cmd.Command.internal_static_command_SubscribeCommandEventsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cmd.Command.internal_static_command_SubscribeCommandEventsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cmd.SubscribeCommandEventsRequest.class, cmd.SubscribeCommandEventsRequest.Builder.class);
    }

    // Construct using cmd.SubscribeCommandEventsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = 0L;

      groupIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cmd.Command.internal_static_command_SubscribeCommandEventsRequest_descriptor;
    }

    @java.lang.Override
    public cmd.SubscribeCommandEventsRequest getDefaultInstanceForType() {
      return cmd.SubscribeCommandEventsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public cmd.SubscribeCommandEventsRequest build() {
      cmd.SubscribeCommandEventsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cmd.SubscribeCommandEventsRequest buildPartial() {
      cmd.SubscribeCommandEventsRequest result = new cmd.SubscribeCommandEventsRequest(this);
      int from_bitField0_ = bitField0_;
      result.userId_ = userId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        groupIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.groupIds_ = groupIds_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cmd.SubscribeCommandEventsRequest) {
        return mergeFrom((cmd.SubscribeCommandEventsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cmd.SubscribeCommandEventsRequest other) {
      if (other == cmd.SubscribeCommandEventsRequest.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.groupIds_.isEmpty()) {
        if (groupIds_.isEmpty()) {
          groupIds_ = other.groupIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureGroupIdsIsMutable();
          groupIds_.addAll(other.groupIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readInt64();

              break;
            } // case 8
            case 16: {
              long v = input.readInt64();
              ensureGroupIdsIsMutable();
              groupIds_.addLong(v);
              break;
            } // case 16
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureGroupIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                groupIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <code>int64 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList groupIds_ = emptyLongList();
    private void ensureGroupIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        groupIds_ = mutableCopy(groupIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 group_ids = 2;</code>
     * @return A list containing the groupIds.
     */
    public java.util.List<java.lang.Long>
        getGroupIdsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(groupIds_) : groupIds_;
    }
    /**
     * <code>repeated int64 group_ids = 2;</code>
     * @return The count of groupIds.
     */
    public int getGroupIdsCount() {
      return groupIds_.size();
    }
    /**
     * <code>repeated int64 group_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The groupIds at the given index.
     */
    public long getGroupIds(int index) {
      return groupIds_.getLong(index);
    }
    /**
     * <code>repeated int64 group_ids = 2;</code>
     * @param index The index to set the value at.
     * @param value The groupIds to set.
     * @return This builder for chaining.
     */
    public Builder setGroupIds(
        int index, long value) {
      ensureGroupIdsIsMutable();
      groupIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 group_ids = 2;</code>
     * @param value The groupIds to add.
     * @return This builder for chaining.
     */
    public Builder addGroupIds(long value) {
      ensureGroupIdsIsMutable();
      groupIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 group_ids = 2;</code>
     * @param values The groupIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllGroupIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureGroupIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, groupIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 group_ids = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroupIds() {
      groupIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:command.SubscribeCommandEventsRequest)
  }

  // @@protoc_insertion_point(class_scope:command.SubscribeCommandEventsRequest)
  private static final cmd.SubscribeCommandEventsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cmd.SubscribeCommandEventsRequest();
  }

  public static cmd.SubscribeCommandEventsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscribeCommandEventsRequest>
      PARSER = new com.google.protobuf.AbstractParser<SubscribeCommandEventsRequest>() {
    @java.lang.Override
    public SubscribeCommandEventsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubscribeCommandEventsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubscribeCommandEventsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cmd.SubscribeCommandEventsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

