// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cmd/cmd.proto
// Protobuf Java Version: 4.28.2

package cmd;

public interface UpdateExecutionStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cmd.UpdateExecutionStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
