// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: proto/object/object.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Object structure
type Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     uint64                 `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	OwnerId       uint64                 `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ObjectType    uint64                 `protobuf:"varint,4,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_proto_object_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_proto_object_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_proto_object_object_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Object) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *Object) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Object) GetObjectType() uint64 {
	if x != nil {
		return x.ObjectType
	}
	return 0
}

func (x *Object) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Object) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// CRUD Requests
type CreateObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]string      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateObjectRequest) Reset() {
	*x = CreateObjectRequest{}
	mi := &file_proto_object_object_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjectRequest) ProtoMessage() {}

func (x *CreateObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_object_object_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjectRequest.ProtoReflect.Descriptor instead.
func (*CreateObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_object_object_proto_rawDescGZIP(), []int{1}
}

func (x *CreateObjectRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      uint64                 `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_proto_object_object_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_object_object_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_object_object_proto_rawDescGZIP(), []int{2}
}

func (x *GetObjectRequest) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type UpdateObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      uint64                 `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateObjectRequest) Reset() {
	*x = UpdateObjectRequest{}
	mi := &file_proto_object_object_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObjectRequest) ProtoMessage() {}

func (x *UpdateObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_object_object_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateObjectRequest) Descriptor() ([]byte, []int) {
	return file_proto_object_object_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateObjectRequest) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *UpdateObjectRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Response with object details
type ObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *Object                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectResponse) Reset() {
	*x = ObjectResponse{}
	mi := &file_proto_object_object_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectResponse) ProtoMessage() {}

func (x *ObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_object_object_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectResponse.ProtoReflect.Descriptor instead.
func (*ObjectResponse) Descriptor() ([]byte, []int) {
	return file_proto_object_object_proto_rawDescGZIP(), []int{4}
}

func (x *ObjectResponse) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

// Pagination support for listing objects
type ListObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_proto_object_object_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_object_object_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_proto_object_object_proto_rawDescGZIP(), []int{5}
}

func (x *ListObjectsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListObjectsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListObjectsRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ListObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*Object              `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_proto_object_object_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_object_object_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_proto_object_object_proto_rawDescGZIP(), []int{6}
}

func (x *ListObjectsResponse) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListObjectsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListObjectsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListObjectsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListObjectsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type ExecuteActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      uint64                 `protobuf:"varint,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionRequest) Reset() {
	*x = ExecuteActionRequest{}
	mi := &file_proto_object_object_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionRequest) ProtoMessage() {}

func (x *ExecuteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_object_object_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_object_object_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteActionRequest) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *ExecuteActionRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ExecuteActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*Object              `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionResponse) Reset() {
	*x = ExecuteActionResponse{}
	mi := &file_proto_object_object_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionResponse) ProtoMessage() {}

func (x *ExecuteActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_object_object_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_object_object_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteActionResponse) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

var File_proto_object_object_proto protoreflect.FileDescriptor

const file_proto_object_object_proto_rawDesc = "" +
	"\n" +
	"\x19proto/object/object.proto\x12\x06object\"\xfc\x01\n" +
	"\x06Object\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x04R\tcreatorId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x04R\aownerId\x12\x1f\n" +
	"\vobject_type\x18\x04 \x01(\x04R\n" +
	"objectType\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\x122\n" +
	"\x06fields\x18\x06 \x03(\v2\x1a.object.Object.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\x13CreateObjectRequest\x12?\n" +
	"\x06fields\x18\x01 \x03(\v2'.object.CreateObjectRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x10GetObjectRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x04R\bobjectId\"\xae\x01\n" +
	"\x13UpdateObjectRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x04R\bobjectId\x12?\n" +
	"\x06fields\x18\x02 \x03(\v2'.object.UpdateObjectRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x0eObjectResponse\x12&\n" +
	"\x06object\x18\x01 \x01(\v2\x0e.object.ObjectR\x06object\"\xc0\x01\n" +
	"\x12ListObjectsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12>\n" +
	"\x06fields\x18\x03 \x03(\v2&.object.ListObjectsRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x13ListObjectsResponse\x12(\n" +
	"\aobjects\x18\x01 \x03(\v2\x0e.object.ObjectR\aobjects\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\xb0\x01\n" +
	"\x14ExecuteActionRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\x04R\bactionId\x12@\n" +
	"\x06fields\x18\x02 \x03(\v2(.object.ExecuteActionRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x15ExecuteActionResponse\x12(\n" +
	"\aobjects\x18\x01 \x03(\v2\x0e.object.ObjectR\aobjects2\xee\x02\n" +
	"\rObjectService\x12C\n" +
	"\fCreateObject\x12\x1b.object.CreateObjectRequest\x1a\x16.object.ObjectResponse\x12=\n" +
	"\tGetObject\x12\x18.object.GetObjectRequest\x1a\x16.object.ObjectResponse\x12C\n" +
	"\fUpdateObject\x12\x1b.object.UpdateObjectRequest\x1a\x16.object.ObjectResponse\x12F\n" +
	"\vListObjects\x12\x1a.object.ListObjectsRequest\x1a\x1b.object.ListObjectsResponse\x12L\n" +
	"\rExecuteAction\x12\x1c.object.ExecuteActionRequest\x1a\x1d.object.ExecuteActionResponseB \n" +
	"\x03objB\x03ObjP\x01Z\fobject/proto\xa2\x02\x03OBJb\x06proto3"

var (
	file_proto_object_object_proto_rawDescOnce sync.Once
	file_proto_object_object_proto_rawDescData []byte
)

func file_proto_object_object_proto_rawDescGZIP() []byte {
	file_proto_object_object_proto_rawDescOnce.Do(func() {
		file_proto_object_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_object_object_proto_rawDesc), len(file_proto_object_object_proto_rawDesc)))
	})
	return file_proto_object_object_proto_rawDescData
}

var file_proto_object_object_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_object_object_proto_goTypes = []any{
	(*Object)(nil),                // 0: object.Object
	(*CreateObjectRequest)(nil),   // 1: object.CreateObjectRequest
	(*GetObjectRequest)(nil),      // 2: object.GetObjectRequest
	(*UpdateObjectRequest)(nil),   // 3: object.UpdateObjectRequest
	(*ObjectResponse)(nil),        // 4: object.ObjectResponse
	(*ListObjectsRequest)(nil),    // 5: object.ListObjectsRequest
	(*ListObjectsResponse)(nil),   // 6: object.ListObjectsResponse
	(*ExecuteActionRequest)(nil),  // 7: object.ExecuteActionRequest
	(*ExecuteActionResponse)(nil), // 8: object.ExecuteActionResponse
	nil,                           // 9: object.Object.FieldsEntry
	nil,                           // 10: object.CreateObjectRequest.FieldsEntry
	nil,                           // 11: object.UpdateObjectRequest.FieldsEntry
	nil,                           // 12: object.ListObjectsRequest.FieldsEntry
	nil,                           // 13: object.ExecuteActionRequest.FieldsEntry
}
var file_proto_object_object_proto_depIdxs = []int32{
	9,  // 0: object.Object.fields:type_name -> object.Object.FieldsEntry
	10, // 1: object.CreateObjectRequest.fields:type_name -> object.CreateObjectRequest.FieldsEntry
	11, // 2: object.UpdateObjectRequest.fields:type_name -> object.UpdateObjectRequest.FieldsEntry
	0,  // 3: object.ObjectResponse.object:type_name -> object.Object
	12, // 4: object.ListObjectsRequest.fields:type_name -> object.ListObjectsRequest.FieldsEntry
	0,  // 5: object.ListObjectsResponse.objects:type_name -> object.Object
	13, // 6: object.ExecuteActionRequest.fields:type_name -> object.ExecuteActionRequest.FieldsEntry
	0,  // 7: object.ExecuteActionResponse.objects:type_name -> object.Object
	1,  // 8: object.ObjectService.CreateObject:input_type -> object.CreateObjectRequest
	2,  // 9: object.ObjectService.GetObject:input_type -> object.GetObjectRequest
	3,  // 10: object.ObjectService.UpdateObject:input_type -> object.UpdateObjectRequest
	5,  // 11: object.ObjectService.ListObjects:input_type -> object.ListObjectsRequest
	7,  // 12: object.ObjectService.ExecuteAction:input_type -> object.ExecuteActionRequest
	4,  // 13: object.ObjectService.CreateObject:output_type -> object.ObjectResponse
	4,  // 14: object.ObjectService.GetObject:output_type -> object.ObjectResponse
	4,  // 15: object.ObjectService.UpdateObject:output_type -> object.ObjectResponse
	6,  // 16: object.ObjectService.ListObjects:output_type -> object.ListObjectsResponse
	8,  // 17: object.ObjectService.ExecuteAction:output_type -> object.ExecuteActionResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_object_object_proto_init() }
func file_proto_object_object_proto_init() {
	if File_proto_object_object_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_object_object_proto_rawDesc), len(file_proto_object_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_object_object_proto_goTypes,
		DependencyIndexes: file_proto_object_object_proto_depIdxs,
		MessageInfos:      file_proto_object_object_proto_msgTypes,
	}.Build()
	File_proto_object_object_proto = out.File
	file_proto_object_object_proto_goTypes = nil
	file_proto_object_object_proto_depIdxs = nil
}
