// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: command/command.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------- ENUMS ----------------
type ExecutionStatus int32

const (
	ExecutionStatus_UNKNOWN              ExecutionStatus = 0
	ExecutionStatus_PENDING              ExecutionStatus = 1
	ExecutionStatus_RUNNING              ExecutionStatus = 2
	ExecutionStatus_SUCCESS              ExecutionStatus = 3
	ExecutionStatus_FAILED               ExecutionStatus = 4
	ExecutionStatus_CANCELLED            ExecutionStatus = 5
	ExecutionStatus_CANCELLED_BY_TIMEOUT ExecutionStatus = 6
	ExecutionStatus_NOT_PERMITTED        ExecutionStatus = 7
	ExecutionStatus_EXECUTORS_NOT_FOUND  ExecutionStatus = 8
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "RUNNING",
		3: "SUCCESS",
		4: "FAILED",
		5: "CANCELLED",
		6: "CANCELLED_BY_TIMEOUT",
		7: "NOT_PERMITTED",
		8: "EXECUTORS_NOT_FOUND",
	}
	ExecutionStatus_value = map[string]int32{
		"UNKNOWN":              0,
		"PENDING":              1,
		"RUNNING":              2,
		"SUCCESS":              3,
		"FAILED":               4,
		"CANCELLED":            5,
		"CANCELLED_BY_TIMEOUT": 6,
		"NOT_PERMITTED":        7,
		"EXECUTORS_NOT_FOUND":  8,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_command_command_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_command_command_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{0}
}

type UserRole int32

const (
	UserRole_VIEWER   UserRole = 0
	UserRole_EXECUTOR UserRole = 1
	UserRole_ADMIN    UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "VIEWER",
		1: "EXECUTOR",
		2: "ADMIN",
	}
	UserRole_value = map[string]int32{
		"VIEWER":   0,
		"EXECUTOR": 1,
		"ADMIN":    2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_command_command_proto_enumTypes[1].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_command_command_proto_enumTypes[1]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{1}
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupsResponse) Reset() {
	*x = GroupsResponse{}
	mi := &file_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupsResponse) ProtoMessage() {}

func (x *GroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupsResponse.ProtoReflect.Descriptor instead.
func (*GroupsResponse) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *GroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRequest) Reset() {
	*x = GroupRequest{}
	mi := &file_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRequest) ProtoMessage() {}

func (x *GroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRequest.ProtoReflect.Descriptor instead.
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *GroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type UserGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Role          UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=command.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroupRequest) Reset() {
	*x = UserGroupRequest{}
	mi := &file_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupRequest) ProtoMessage() {}

func (x *UserGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupRequest.ProtoReflect.Descriptor instead.
func (*UserGroupRequest) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{3}
}

func (x *UserGroupRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UserGroupRequest) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_VIEWER
}

// ------------- COMMAND TEMPLATES -------------
type ParameterField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Options       []string               `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	Required      bool                   `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"`
	Multiline     bool                   `protobuf:"varint,8,opt,name=multiline,proto3" json:"multiline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterField) Reset() {
	*x = ParameterField{}
	mi := &file_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterField) ProtoMessage() {}

func (x *ParameterField) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterField.ProtoReflect.Descriptor instead.
func (*ParameterField) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *ParameterField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ParameterField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ParameterField) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ParameterField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParameterField) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ParameterField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ParameterField) GetMultiline() bool {
	if x != nil {
		return x.Multiline
	}
	return false
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields        []*ParameterField      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Command) GetFields() []*ParameterField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type AddCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*ParameterField      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommandRequest) Reset() {
	*x = AddCommandRequest{}
	mi := &file_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommandRequest) ProtoMessage() {}

func (x *AddCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommandRequest.ProtoReflect.Descriptor instead.
func (*AddCommandRequest) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *AddCommandRequest) GetFields() []*ParameterField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DeleteCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommandRequest) Reset() {
	*x = DeleteCommandRequest{}
	mi := &file_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommandRequest) ProtoMessage() {}

func (x *DeleteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommandRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommandRequest) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCommandRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ------------- COMMAND EXECUTION -------------
type ExecuteRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CommandId          uint64                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	OverrideParameters map[string]string      `protobuf:"bytes,2,rep,name=override_parameters,json=overrideParameters,proto3" json:"override_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_command_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteRequest) GetCommandId() uint64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *ExecuteRequest) GetOverrideParameters() map[string]string {
	if x != nil {
		return x.OverrideParameters
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   uint64                 `protobuf:"varint,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	QueueStatus   ExecutionStatus        `protobuf:"varint,2,opt,name=queue_status,json=queueStatus,proto3,enum=command.ExecutionStatus" json:"queue_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_command_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteResponse) GetExecutionId() uint64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *ExecuteResponse) GetQueueStatus() ExecutionStatus {
	if x != nil {
		return x.QueueStatus
	}
	return ExecutionStatus_UNKNOWN
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   uint64                 `protobuf:"varint,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_command_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{10}
}

func (x *CancelRequest) GetExecutionId() uint64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_command_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{11}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   uint64                 `protobuf:"varint,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryRequest) Reset() {
	*x = RetryRequest{}
	mi := &file_command_command_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryRequest) ProtoMessage() {}

func (x *RetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryRequest.ProtoReflect.Descriptor instead.
func (*RetryRequest) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{12}
}

func (x *RetryRequest) GetExecutionId() uint64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

type DryRunResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     uint64                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DryRunResult) Reset() {
	*x = DryRunResult{}
	mi := &file_command_command_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DryRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DryRunResult) ProtoMessage() {}

func (x *DryRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DryRunResult.ProtoReflect.Descriptor instead.
func (*DryRunResult) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{13}
}

func (x *DryRunResult) GetCommandId() uint64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

// ------------- LOG STREAMING -------------
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_command_command_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{14}
}

type CommandLog struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId         uint64                 `protobuf:"varint,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	CommandId           uint64                 `protobuf:"varint,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Output              string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Status              ExecutionStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=command.ExecutionStatus" json:"status,omitempty"`
	Timestamp           uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EffectiveParameters map[string]string      `protobuf:"bytes,6,rep,name=effective_parameters,json=effectiveParameters,proto3" json:"effective_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResultCode          string                 `protobuf:"bytes,7,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CommandLog) Reset() {
	*x = CommandLog{}
	mi := &file_command_command_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandLog) ProtoMessage() {}

func (x *CommandLog) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandLog.ProtoReflect.Descriptor instead.
func (*CommandLog) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{15}
}

func (x *CommandLog) GetExecutionId() uint64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *CommandLog) GetCommandId() uint64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *CommandLog) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandLog) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_UNKNOWN
}

func (x *CommandLog) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CommandLog) GetEffectiveParameters() map[string]string {
	if x != nil {
		return x.EffectiveParameters
	}
	return nil
}

func (x *CommandLog) GetResultCode() string {
	if x != nil {
		return x.ResultCode
	}
	return ""
}

// ------------- STATUS UPDATE & EVENT SUBSCRIPTION -------------
type UpdateExecutionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   uint64                 `protobuf:"varint,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        ExecutionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=command.ExecutionStatus" json:"status,omitempty"`
	ResultCode    string                 `protobuf:"bytes,3,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExecutionStatusRequest) Reset() {
	*x = UpdateExecutionStatusRequest{}
	mi := &file_command_command_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExecutionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExecutionStatusRequest) ProtoMessage() {}

func (x *UpdateExecutionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExecutionStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateExecutionStatusRequest) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateExecutionStatusRequest) GetExecutionId() uint64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *UpdateExecutionStatusRequest) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_UNKNOWN
}

func (x *UpdateExecutionStatusRequest) GetResultCode() string {
	if x != nil {
		return x.ResultCode
	}
	return ""
}

type UpdateExecutionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExecutionStatusResponse) Reset() {
	*x = UpdateExecutionStatusResponse{}
	mi := &file_command_command_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExecutionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExecutionStatusResponse) ProtoMessage() {}

func (x *UpdateExecutionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExecutionStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateExecutionStatusResponse) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateExecutionStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribeCommandEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeCommandEventsRequest) Reset() {
	*x = SubscribeCommandEventsRequest{}
	mi := &file_command_command_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeCommandEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeCommandEventsRequest) ProtoMessage() {}

func (x *SubscribeCommandEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeCommandEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeCommandEventsRequest) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{18}
}

type CommandEvent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId         uint64                 `protobuf:"varint,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	CommandId           uint64                 `protobuf:"varint,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	EffectiveParameters map[string]string      `protobuf:"bytes,3,rep,name=effective_parameters,json=effectiveParameters,proto3" json:"effective_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp           uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CommandEvent) Reset() {
	*x = CommandEvent{}
	mi := &file_command_command_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEvent) ProtoMessage() {}

func (x *CommandEvent) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEvent.ProtoReflect.Descriptor instead.
func (*CommandEvent) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{19}
}

func (x *CommandEvent) GetExecutionId() uint64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *CommandEvent) GetCommandId() uint64 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *CommandEvent) GetEffectiveParameters() map[string]string {
	if x != nil {
		return x.EffectiveParameters
	}
	return nil
}

func (x *CommandEvent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_command_command_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{20}
}

func (x *Object) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Object) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type UserGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Role          UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=command.UserRole" json:"role,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGroupResponse) Reset() {
	*x = UserGroupResponse{}
	mi := &file_command_command_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGroupResponse) ProtoMessage() {}

func (x *UserGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGroupResponse.ProtoReflect.Descriptor instead.
func (*UserGroupResponse) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{21}
}

func (x *UserGroupResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserGroupResponse) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UserGroupResponse) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_VIEWER
}

func (x *UserGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_command_command_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{22}
}

var File_command_command_proto protoreflect.FileDescriptor

const file_command_command_proto_rawDesc = "" +
	"\n" +
	"\x15command/command.proto\x12\acommand\"X\n" +
	"\x05Group\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"8\n" +
	"\x0eGroupsResponse\x12&\n" +
	"\x06groups\x18\x01 \x03(\v2\x0e.command.GroupR\x06groups\")\n" +
	"\fGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\"m\n" +
	"\x10UserGroupRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12%\n" +
	"\x04role\x18\x03 \x01(\x0e2\x11.command.UserRoleR\x04role\"\xe9\x01\n" +
	"\x0eParameterField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aoptions\x18\x06 \x03(\tR\aoptions\x12\x1a\n" +
	"\brequired\x18\a \x01(\bR\brequired\x12\x1c\n" +
	"\tmultiline\x18\b \x01(\bR\tmultiline\"J\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12/\n" +
	"\x06fields\x18\x02 \x03(\v2\x17.command.ParameterFieldR\x06fields\"D\n" +
	"\x11AddCommandRequest\x12/\n" +
	"\x06fields\x18\x01 \x03(\v2\x17.command.ParameterFieldR\x06fields\"&\n" +
	"\x14DeleteCommandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xd8\x01\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x04R\tcommandId\x12`\n" +
	"\x13override_parameters\x18\x02 \x03(\v2/.command.ExecuteRequest.OverrideParametersEntryR\x12overrideParameters\x1aE\n" +
	"\x17OverrideParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x0fExecuteResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\x04R\vexecutionId\x12;\n" +
	"\fqueue_status\x18\x02 \x01(\x0e2\x18.command.ExecutionStatusR\vqueueStatus\"2\n" +
	"\rCancelRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\x04R\vexecutionId\"*\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\fRetryRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\x04R\vexecutionId\"-\n" +
	"\fDryRunResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\x04R\tcommandId\"\x12\n" +
	"\x10SubscribeRequest\"\x80\x03\n" +
	"\n" +
	"CommandLog\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\x04R\vexecutionId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\x04R\tcommandId\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.command.ExecutionStatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x12_\n" +
	"\x14effective_parameters\x18\x06 \x03(\v2,.command.CommandLog.EffectiveParametersEntryR\x13effectiveParameters\x12\x1f\n" +
	"\vresult_code\x18\a \x01(\tR\n" +
	"resultCode\x1aF\n" +
	"\x18EffectiveParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\x1cUpdateExecutionStatusRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\x04R\vexecutionId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.command.ExecutionStatusR\x06status\x12\x1f\n" +
	"\vresult_code\x18\x03 \x01(\tR\n" +
	"resultCode\"9\n" +
	"\x1dUpdateExecutionStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1f\n" +
	"\x1dSubscribeCommandEventsRequest\"\x99\x02\n" +
	"\fCommandEvent\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\x04R\vexecutionId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\x04R\tcommandId\x12a\n" +
	"\x14effective_parameters\x18\x03 \x03(\v2..command.CommandEvent.EffectiveParametersEntryR\x13effectiveParameters\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x1aF\n" +
	"\x18EffectiveParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\x06Object\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x123\n" +
	"\x06fields\x18\x02 \x03(\v2\x1b.command.Object.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\x11UserGroupResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12%\n" +
	"\x04role\x18\x03 \x01(\x0e2\x11.command.UserRoleR\x04role\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\a\n" +
	"\x05Empty*\xa6\x01\n" +
	"\x0fExecutionStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\v\n" +
	"\aSUCCESS\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05\x12\x18\n" +
	"\x14CANCELLED_BY_TIMEOUT\x10\x06\x12\x11\n" +
	"\rNOT_PERMITTED\x10\a\x12\x17\n" +
	"\x13EXECUTORS_NOT_FOUND\x10\b*/\n" +
	"\bUserRole\x12\n" +
	"\n" +
	"\x06VIEWER\x10\x00\x12\f\n" +
	"\bEXECUTOR\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x022\x8e\a\n" +
	"\x0eCommandService\x12.\n" +
	"\n" +
	"ListGroups\x12\x0e.command.Empty\x1a\x0e.command.Group0\x01\x124\n" +
	"\vDeleteGroup\x12\x15.command.GroupRequest\x1a\x0e.command.Group\x12G\n" +
	"\x0eAddUserToGroup\x12\x19.command.UserGroupRequest\x1a\x1a.command.UserGroupResponse\x12L\n" +
	"\x13RemoveUserFromGroup\x12\x19.command.UserGroupRequest\x1a\x1a.command.UserGroupResponse\x12B\n" +
	"\x12AddCommandTemplate\x12\x1a.command.AddCommandRequest\x1a\x10.command.Command\x12H\n" +
	"\x15DeleteCommandTemplate\x12\x1d.command.DeleteCommandRequest\x1a\x10.command.Command\x12<\n" +
	"\aExecute\x12\x17.command.ExecuteRequest\x1a\x18.command.ExecuteResponse\x129\n" +
	"\x06Cancel\x12\x16.command.CancelRequest\x1a\x17.command.CancelResponse\x128\n" +
	"\x05Retry\x12\x15.command.RetryRequest\x1a\x18.command.ExecuteResponse\x128\n" +
	"\x06DryRun\x12\x17.command.ExecuteRequest\x1a\x15.command.DryRunResult\x12f\n" +
	"\x15UpdateExecutionStatus\x12%.command.UpdateExecutionStatusRequest\x1a&.command.UpdateExecutionStatusResponse\x12A\n" +
	"\rSubscribeLogs\x12\x19.command.SubscribeRequest\x1a\x13.command.CommandLog0\x01\x12Y\n" +
	"\x16SubscribeCommandEvents\x12&.command.SubscribeCommandEventsRequest\x1a\x15.command.CommandEvent0\x01B-\n" +
	"\acommandB\aCommandP\x01Z\rcommand/proto\xa2\x02\aCOMMANDb\x06proto3"

var (
	file_command_command_proto_rawDescOnce sync.Once
	file_command_command_proto_rawDescData []byte
)

func file_command_command_proto_rawDescGZIP() []byte {
	file_command_command_proto_rawDescOnce.Do(func() {
		file_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_command_proto_rawDesc), len(file_command_command_proto_rawDesc)))
	})
	return file_command_command_proto_rawDescData
}

var file_command_command_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_command_command_proto_goTypes = []any{
	(ExecutionStatus)(0),                  // 0: command.ExecutionStatus
	(UserRole)(0),                         // 1: command.UserRole
	(*Group)(nil),                         // 2: command.Group
	(*GroupsResponse)(nil),                // 3: command.GroupsResponse
	(*GroupRequest)(nil),                  // 4: command.GroupRequest
	(*UserGroupRequest)(nil),              // 5: command.UserGroupRequest
	(*ParameterField)(nil),                // 6: command.ParameterField
	(*Command)(nil),                       // 7: command.Command
	(*AddCommandRequest)(nil),             // 8: command.AddCommandRequest
	(*DeleteCommandRequest)(nil),          // 9: command.DeleteCommandRequest
	(*ExecuteRequest)(nil),                // 10: command.ExecuteRequest
	(*ExecuteResponse)(nil),               // 11: command.ExecuteResponse
	(*CancelRequest)(nil),                 // 12: command.CancelRequest
	(*CancelResponse)(nil),                // 13: command.CancelResponse
	(*RetryRequest)(nil),                  // 14: command.RetryRequest
	(*DryRunResult)(nil),                  // 15: command.DryRunResult
	(*SubscribeRequest)(nil),              // 16: command.SubscribeRequest
	(*CommandLog)(nil),                    // 17: command.CommandLog
	(*UpdateExecutionStatusRequest)(nil),  // 18: command.UpdateExecutionStatusRequest
	(*UpdateExecutionStatusResponse)(nil), // 19: command.UpdateExecutionStatusResponse
	(*SubscribeCommandEventsRequest)(nil), // 20: command.SubscribeCommandEventsRequest
	(*CommandEvent)(nil),                  // 21: command.CommandEvent
	(*Object)(nil),                        // 22: command.Object
	(*UserGroupResponse)(nil),             // 23: command.UserGroupResponse
	(*Empty)(nil),                         // 24: command.Empty
	nil,                                   // 25: command.ExecuteRequest.OverrideParametersEntry
	nil,                                   // 26: command.CommandLog.EffectiveParametersEntry
	nil,                                   // 27: command.CommandEvent.EffectiveParametersEntry
	nil,                                   // 28: command.Object.FieldsEntry
}
var file_command_command_proto_depIdxs = []int32{
	2,  // 0: command.GroupsResponse.groups:type_name -> command.Group
	1,  // 1: command.UserGroupRequest.role:type_name -> command.UserRole
	6,  // 2: command.Command.fields:type_name -> command.ParameterField
	6,  // 3: command.AddCommandRequest.fields:type_name -> command.ParameterField
	25, // 4: command.ExecuteRequest.override_parameters:type_name -> command.ExecuteRequest.OverrideParametersEntry
	0,  // 5: command.ExecuteResponse.queue_status:type_name -> command.ExecutionStatus
	0,  // 6: command.CommandLog.status:type_name -> command.ExecutionStatus
	26, // 7: command.CommandLog.effective_parameters:type_name -> command.CommandLog.EffectiveParametersEntry
	0,  // 8: command.UpdateExecutionStatusRequest.status:type_name -> command.ExecutionStatus
	27, // 9: command.CommandEvent.effective_parameters:type_name -> command.CommandEvent.EffectiveParametersEntry
	28, // 10: command.Object.fields:type_name -> command.Object.FieldsEntry
	1,  // 11: command.UserGroupResponse.role:type_name -> command.UserRole
	24, // 12: command.CommandService.ListGroups:input_type -> command.Empty
	4,  // 13: command.CommandService.DeleteGroup:input_type -> command.GroupRequest
	5,  // 14: command.CommandService.AddUserToGroup:input_type -> command.UserGroupRequest
	5,  // 15: command.CommandService.RemoveUserFromGroup:input_type -> command.UserGroupRequest
	8,  // 16: command.CommandService.AddCommandTemplate:input_type -> command.AddCommandRequest
	9,  // 17: command.CommandService.DeleteCommandTemplate:input_type -> command.DeleteCommandRequest
	10, // 18: command.CommandService.Execute:input_type -> command.ExecuteRequest
	12, // 19: command.CommandService.Cancel:input_type -> command.CancelRequest
	14, // 20: command.CommandService.Retry:input_type -> command.RetryRequest
	10, // 21: command.CommandService.DryRun:input_type -> command.ExecuteRequest
	18, // 22: command.CommandService.UpdateExecutionStatus:input_type -> command.UpdateExecutionStatusRequest
	16, // 23: command.CommandService.SubscribeLogs:input_type -> command.SubscribeRequest
	20, // 24: command.CommandService.SubscribeCommandEvents:input_type -> command.SubscribeCommandEventsRequest
	2,  // 25: command.CommandService.ListGroups:output_type -> command.Group
	2,  // 26: command.CommandService.DeleteGroup:output_type -> command.Group
	23, // 27: command.CommandService.AddUserToGroup:output_type -> command.UserGroupResponse
	23, // 28: command.CommandService.RemoveUserFromGroup:output_type -> command.UserGroupResponse
	7,  // 29: command.CommandService.AddCommandTemplate:output_type -> command.Command
	7,  // 30: command.CommandService.DeleteCommandTemplate:output_type -> command.Command
	11, // 31: command.CommandService.Execute:output_type -> command.ExecuteResponse
	13, // 32: command.CommandService.Cancel:output_type -> command.CancelResponse
	11, // 33: command.CommandService.Retry:output_type -> command.ExecuteResponse
	15, // 34: command.CommandService.DryRun:output_type -> command.DryRunResult
	19, // 35: command.CommandService.UpdateExecutionStatus:output_type -> command.UpdateExecutionStatusResponse
	17, // 36: command.CommandService.SubscribeLogs:output_type -> command.CommandLog
	21, // 37: command.CommandService.SubscribeCommandEvents:output_type -> command.CommandEvent
	25, // [25:38] is the sub-list for method output_type
	12, // [12:25] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_command_command_proto_init() }
func file_command_command_proto_init() {
	if File_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_command_proto_rawDesc), len(file_command_command_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_command_proto_goTypes,
		DependencyIndexes: file_command_command_proto_depIdxs,
		EnumInfos:         file_command_command_proto_enumTypes,
		MessageInfos:      file_command_command_proto_msgTypes,
	}.Build()
	File_command_command_proto = out.File
	file_command_command_proto_goTypes = nil
	file_command_command_proto_depIdxs = nil
}
