// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/auth.proto
// Protobuf Java Version: 4.33.0

package auth;

@com.google.protobuf.Generated
public interface AppInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.AppInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>bool is_logged_in = 2;</code>
   * @return The isLoggedIn.
   */
  boolean getIsLoggedIn();
}
