// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/auth.proto
// Protobuf Java Version: 4.28.2

package auth;

public final class Auth {
  private Auth() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Auth.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LinkDeviceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_LinkDeviceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_AppInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_AppInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_Device_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_Device_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_UserInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_UserInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_SignalMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_SignalMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_SignalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_SignalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_SignalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_SignalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_DeleteDeviceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_DeleteDeviceRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017auth/auth.proto\022\004auth\032\033google/protobuf" +
      "/empty.proto\"2\n\017RegisterRequest\022\r\n\005email" +
      "\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"#\n\020RegisterResp" +
      "onse\022\017\n\007user_id\030\001 \001(\004\"D\n\014LoginRequest\022\r\n" +
      "\005email\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\023\n\013device" +
      "_name\030\003 \001(\t\"7\n\021LinkDeviceRequest\022\023\n\013devi" +
      "ce_name\030\001 \001(\t\022\r\n\005token\030\002 \001(\t\"\036\n\rLoginRes" +
      "ponse\022\r\n\005token\030\001 \001(\t\"8\n\017AppInfoResponse\022" +
      "\017\n\007version\030\001 \001(\t\022\024\n\014is_logged_in\030\002 \001(\010\"\"" +
      "\n\006Device\022\n\n\002id\030\001 \001(\004\022\014\n\004name\030\002 \001(\t\"L\n\020Us" +
      "erInfoResponse\022\n\n\002id\030\001 \001(\004\022\r\n\005email\030\002 \001(" +
      "\t\022\035\n\007devices\030\003 \003(\0132\014.auth.Device\"_\n\rSign" +
      "alMessage\022\037\n\004type\030\001 \001(\0162\021.auth.MessageTy" +
      "pe\022\016\n\006source\030\002 \001(\004\022\016\n\006target\030\003 \001(\004\022\r\n\005va" +
      "lue\030\004 \001(\t\"5\n\rSignalRequest\022$\n\007message\030\001 " +
      "\001(\0132\023.auth.SignalMessage\"6\n\016SignalRespon" +
      "se\022$\n\007message\030\001 \001(\0132\023.auth.SignalMessage" +
      "\"!\n\023DeleteDeviceRequest\022\n\n\002id\030\001 \001(\004*N\n\013M" +
      "essageType\022\013\n\007UNKNOWN\020\000\022\t\n\005OFFER\020\001\022\n\n\006AN" +
      "SWER\020\002\022\021\n\rICE_CANDIDATE\020\003\022\010\n\004JOIN\020\0042\257\003\n\013" +
      "AuthService\0229\n\010Register\022\025.auth.RegisterR" +
      "equest\032\026.auth.RegisterResponse\0220\n\005Login\022" +
      "\022.auth.LoginRequest\032\023.auth.LoginResponse" +
      "\022:\n\nLinkDevice\022\027.auth.LinkDeviceRequest\032" +
      "\023.auth.LoginResponse\022;\n\nGetAppInfo\022\026.goo" +
      "gle.protobuf.Empty\032\025.auth.AppInfoRespons" +
      "e\022=\n\013GetUserInfo\022\026.google.protobuf.Empty" +
      "\032\026.auth.UserInfoResponse\0228\n\007Connect\022\023.au" +
      "th.SignalRequest\032\024.auth.SignalResponse(\001" +
      "0\001\022A\n\014DeleteDevice\022\031.auth.DeleteDeviceRe" +
      "quest\032\026.google.protobuf.EmptyB!\n\004authB\004A" +
      "uthP\001Z\nauth/proto\242\002\004AUTHb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_auth_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_auth_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_RegisterRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_auth_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_auth_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_RegisterResponse_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_auth_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_auth_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_LoginRequest_descriptor,
        new java.lang.String[] { "Email", "Password", "DeviceName", });
    internal_static_auth_LinkDeviceRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_auth_LinkDeviceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_LinkDeviceRequest_descriptor,
        new java.lang.String[] { "DeviceName", "Token", });
    internal_static_auth_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_auth_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_LoginResponse_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_auth_AppInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_auth_AppInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_AppInfoResponse_descriptor,
        new java.lang.String[] { "Version", "IsLoggedIn", });
    internal_static_auth_Device_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_auth_Device_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_Device_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_auth_UserInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_auth_UserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_UserInfoResponse_descriptor,
        new java.lang.String[] { "Id", "Email", "Devices", });
    internal_static_auth_SignalMessage_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_auth_SignalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_SignalMessage_descriptor,
        new java.lang.String[] { "Type", "Source", "Target", "Value", });
    internal_static_auth_SignalRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_auth_SignalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_SignalRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_auth_SignalResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_auth_SignalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_SignalResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_auth_DeleteDeviceRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_auth_DeleteDeviceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_DeleteDeviceRequest_descriptor,
        new java.lang.String[] { "Id", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
