// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/auth.proto
// Protobuf Java Version: 4.33.0

package auth;

@com.google.protobuf.Generated
public final class Auth extends com.google.protobuf.GeneratedFile {
  private Auth() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "Auth");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_AppInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_AppInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_Device_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_Device_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_UserInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_UserInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_SignalMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_SignalMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_SignalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_SignalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_SignalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_SignalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_Envelope_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_Envelope_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_QRCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_QRCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_Healthcheck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_Healthcheck_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_auth_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017auth/auth.proto\022\004auth\032\033google/protobuf" +
      "/empty.proto\"2\n\017RegisterRequest\022\r\n\005email" +
      "\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"#\n\020RegisterResp" +
      "onse\022\017\n\007user_id\030\001 \001(\004\"D\n\014LoginRequest\022\r\n" +
      "\005email\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\023\n\013device" +
      "_name\030\003 \001(\t\"\036\n\rLoginResponse\022\r\n\005token\030\001 " +
      "\001(\t\"8\n\017AppInfoResponse\022\017\n\007version\030\001 \001(\t\022" +
      "\024\n\014is_logged_in\030\002 \001(\010\"3\n\006Device\022\n\n\002id\030\001 " +
      "\001(\004\022\014\n\004name\030\002 \001(\t\022\017\n\007contact\030\003 \001(\010\"L\n\020Us" +
      "erInfoResponse\022\n\n\002id\030\001 \001(\004\022\r\n\005email\030\002 \001(" +
      "\t\022\035\n\007devices\030\003 \003(\0132\014.auth.Device\"_\n\rSign" +
      "alMessage\022\037\n\004type\030\001 \001(\0162\021.auth.MessageTy" +
      "pe\022\016\n\006source\030\002 \001(\004\022\016\n\006target\030\003 \001(\004\022\r\n\005va" +
      "lue\030\004 \001(\014\"5\n\rSignalRequest\022$\n\007message\030\001 " +
      "\001(\0132\023.auth.SignalMessage\"6\n\016SignalRespon" +
      "se\022$\n\007message\030\001 \001(\0132\023.auth.SignalMessage" +
      "\"\"\n\rLogoutRequest\022\021\n\tdevice_id\030\001 \001(\004\"!\n\016" +
      "LogoutResponse\022\017\n\007success\030\001 \001(\010\"{\n\010Envel" +
      "ope\022\n\n\002id\030\001 \001(\r\022\'\n\014payload_type\030\002 \001(\0162\021." +
      "auth.PayloadType\022\017\n\007payload\030\003 \001(\014\022\023\n\013chu" +
      "nk_index\030\004 \001(\r\022\024\n\014total_chunks\030\005 \001(\r\"q\n\t" +
      "QRCommand\022\017\n\007command\030\001 \001(\004\022\020\n\010argument\030\002" +
      " \001(\004\022\016\n\006crc32c\030\003 \001(\r\022\021\n\tsignature\030\004 \001(\014\022" +
      "\022\n\npublic_key\030\005 \001(\014\022\n\n\002ts\030\006 \001(\004\";\n\013Healt" +
      "hcheck\022\n\n\002ts\030\001 \001(\004\022\016\n\006sender\030\002 \001(\004\022\020\n\010re" +
      "ceiver\030\003 \001(\004\"\007\n\005Empty*z\n\013MessageType\022\010\n\004" +
      "JOIN\020\000\022\010\n\004LINK\020\001\022\t\n\005OFFER\020\002\022\n\n\006ANSWER\020\003\022" +
      "\021\n\rICE_CANDIDATE\020\004\022\016\n\nNEW_DEVICE\020\005\022\016\n\nNO" +
      "T_JOINED\020\006\022\r\n\tUSER_INFO\020\007*x\n\013PayloadType" +
      "\022\013\n\007UNKNOWN\020\000\022\017\n\013HEALTHCHECK\020\001\022\023\n\017HEALTH" +
      "CHECK_ACK\020\002\022\022\n\016SIGNAL_MESSAGE\020\003\022\016\n\nQR_CO" +
      "MMAND\020\004\022\010\n\004JPEG\020\005\022\010\n\004H265\020\0062\317\002\n\013AuthServ" +
      "ice\0229\n\010Register\022\025.auth.RegisterRequest\032\026" +
      ".auth.RegisterResponse\0220\n\005Login\022\022.auth.L" +
      "oginRequest\032\023.auth.LoginResponse\0220\n\nGetA" +
      "ppInfo\022\013.auth.Empty\032\025.auth.AppInfoRespon" +
      "se\0222\n\013GetUserInfo\022\013.auth.Empty\032\026.auth.Us" +
      "erInfoResponse\0228\n\007Connect\022\023.auth.SignalR" +
      "equest\032\024.auth.SignalResponse(\0010\001\0223\n\006Logo" +
      "ut\022\023.auth.LogoutRequest\032\024.auth.LogoutRes" +
      "ponseB!\n\004authB\004AuthP\001Z\nauth/proto\242\002\004AUTH" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_auth_RegisterRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_auth_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_RegisterRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_auth_RegisterResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_auth_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_RegisterResponse_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_auth_LoginRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_auth_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_LoginRequest_descriptor,
        new java.lang.String[] { "Email", "Password", "DeviceName", });
    internal_static_auth_LoginResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_auth_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_LoginResponse_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_auth_AppInfoResponse_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_auth_AppInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_AppInfoResponse_descriptor,
        new java.lang.String[] { "Version", "IsLoggedIn", });
    internal_static_auth_Device_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_auth_Device_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_Device_descriptor,
        new java.lang.String[] { "Id", "Name", "Contact", });
    internal_static_auth_UserInfoResponse_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_auth_UserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_UserInfoResponse_descriptor,
        new java.lang.String[] { "Id", "Email", "Devices", });
    internal_static_auth_SignalMessage_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_auth_SignalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_SignalMessage_descriptor,
        new java.lang.String[] { "Type", "Source", "Target", "Value", });
    internal_static_auth_SignalRequest_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_auth_SignalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_SignalRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_auth_SignalResponse_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_auth_SignalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_SignalResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_auth_LogoutRequest_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_auth_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_LogoutRequest_descriptor,
        new java.lang.String[] { "DeviceId", });
    internal_static_auth_LogoutResponse_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_auth_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_LogoutResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_auth_Envelope_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_auth_Envelope_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_Envelope_descriptor,
        new java.lang.String[] { "Id", "PayloadType", "Payload", "ChunkIndex", "TotalChunks", });
    internal_static_auth_QRCommand_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_auth_QRCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_QRCommand_descriptor,
        new java.lang.String[] { "Command", "Argument", "Crc32C", "Signature", "PublicKey", "Ts", });
    internal_static_auth_Healthcheck_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_auth_Healthcheck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_Healthcheck_descriptor,
        new java.lang.String[] { "Ts", "Sender", "Receiver", });
    internal_static_auth_Empty_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_auth_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_auth_Empty_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
