// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/auth.proto
// Protobuf Java Version: 4.33.0

package auth;

@com.google.protobuf.Generated
public interface EnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.Envelope)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.auth.PayloadType payload_type = 2;</code>
   * @return The enum numeric value on the wire for payloadType.
   */
  int getPayloadTypeValue();
  /**
   * <code>.auth.PayloadType payload_type = 2;</code>
   * @return The payloadType.
   */
  auth.PayloadType getPayloadType();

  /**
   * <code>bytes payload = 3;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>uint32 chunk_index = 4;</code>
   * @return The chunkIndex.
   */
  int getChunkIndex();

  /**
   * <code>uint32 total_chunks = 5;</code>
   * @return The totalChunks.
   */
  int getTotalChunks();
}
