// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/auth.proto
// Protobuf Java Version: 4.33.0

package auth;

/**
 * Protobuf type {@code auth.Envelope}
 */
@com.google.protobuf.Generated
public final class Envelope extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:auth.Envelope)
    EnvelopeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "Envelope");
  }
  // Use Envelope.newBuilder() to construct.
  private Envelope(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Envelope() {
    payloadType_ = 0;
    payload_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return auth.Auth.internal_static_auth_Envelope_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return auth.Auth.internal_static_auth_Envelope_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            auth.Envelope.class, auth.Envelope.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int PAYLOAD_TYPE_FIELD_NUMBER = 2;
  private int payloadType_ = 0;
  /**
   * <code>.auth.PayloadType payload_type = 2;</code>
   * @return The enum numeric value on the wire for payloadType.
   */
  @java.lang.Override public int getPayloadTypeValue() {
    return payloadType_;
  }
  /**
   * <code>.auth.PayloadType payload_type = 2;</code>
   * @return The payloadType.
   */
  @java.lang.Override public auth.PayloadType getPayloadType() {
    auth.PayloadType result = auth.PayloadType.forNumber(payloadType_);
    return result == null ? auth.PayloadType.UNRECOGNIZED : result;
  }

  public static final int PAYLOAD_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes payload = 3;</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  public static final int CHUNK_INDEX_FIELD_NUMBER = 4;
  private int chunkIndex_ = 0;
  /**
   * <code>uint32 chunk_index = 4;</code>
   * @return The chunkIndex.
   */
  @java.lang.Override
  public int getChunkIndex() {
    return chunkIndex_;
  }

  public static final int TOTAL_CHUNKS_FIELD_NUMBER = 5;
  private int totalChunks_ = 0;
  /**
   * <code>uint32 total_chunks = 5;</code>
   * @return The totalChunks.
   */
  @java.lang.Override
  public int getTotalChunks() {
    return totalChunks_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeUInt32(1, id_);
    }
    if (payloadType_ != auth.PayloadType.TEXT.getNumber()) {
      output.writeEnum(2, payloadType_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(3, payload_);
    }
    if (chunkIndex_ != 0) {
      output.writeUInt32(4, chunkIndex_);
    }
    if (totalChunks_ != 0) {
      output.writeUInt32(5, totalChunks_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, id_);
    }
    if (payloadType_ != auth.PayloadType.TEXT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, payloadType_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, payload_);
    }
    if (chunkIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, chunkIndex_);
    }
    if (totalChunks_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, totalChunks_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof auth.Envelope)) {
      return super.equals(obj);
    }
    auth.Envelope other = (auth.Envelope) obj;

    if (getId()
        != other.getId()) return false;
    if (payloadType_ != other.payloadType_) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (getChunkIndex()
        != other.getChunkIndex()) return false;
    if (getTotalChunks()
        != other.getTotalChunks()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + PAYLOAD_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + payloadType_;
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (37 * hash) + CHUNK_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getChunkIndex();
    hash = (37 * hash) + TOTAL_CHUNKS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalChunks();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static auth.Envelope parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static auth.Envelope parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static auth.Envelope parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static auth.Envelope parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static auth.Envelope parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static auth.Envelope parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static auth.Envelope parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static auth.Envelope parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static auth.Envelope parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static auth.Envelope parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static auth.Envelope parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static auth.Envelope parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(auth.Envelope prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code auth.Envelope}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:auth.Envelope)
      auth.EnvelopeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return auth.Auth.internal_static_auth_Envelope_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return auth.Auth.internal_static_auth_Envelope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              auth.Envelope.class, auth.Envelope.Builder.class);
    }

    // Construct using auth.Envelope.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      payloadType_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      chunkIndex_ = 0;
      totalChunks_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return auth.Auth.internal_static_auth_Envelope_descriptor;
    }

    @java.lang.Override
    public auth.Envelope getDefaultInstanceForType() {
      return auth.Envelope.getDefaultInstance();
    }

    @java.lang.Override
    public auth.Envelope build() {
      auth.Envelope result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public auth.Envelope buildPartial() {
      auth.Envelope result = new auth.Envelope(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(auth.Envelope result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.payloadType_ = payloadType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.payload_ = payload_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.chunkIndex_ = chunkIndex_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.totalChunks_ = totalChunks_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof auth.Envelope) {
        return mergeFrom((auth.Envelope)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(auth.Envelope other) {
      if (other == auth.Envelope.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.payloadType_ != 0) {
        setPayloadTypeValue(other.getPayloadTypeValue());
      }
      if (!other.getPayload().isEmpty()) {
        setPayload(other.getPayload());
      }
      if (other.getChunkIndex() != 0) {
        setChunkIndex(other.getChunkIndex());
      }
      if (other.getTotalChunks() != 0) {
        setTotalChunks(other.getTotalChunks());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              payloadType_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              payload_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              chunkIndex_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              totalChunks_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private int payloadType_ = 0;
    /**
     * <code>.auth.PayloadType payload_type = 2;</code>
     * @return The enum numeric value on the wire for payloadType.
     */
    @java.lang.Override public int getPayloadTypeValue() {
      return payloadType_;
    }
    /**
     * <code>.auth.PayloadType payload_type = 2;</code>
     * @param value The enum numeric value on the wire for payloadType to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadTypeValue(int value) {
      payloadType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.auth.PayloadType payload_type = 2;</code>
     * @return The payloadType.
     */
    @java.lang.Override
    public auth.PayloadType getPayloadType() {
      auth.PayloadType result = auth.PayloadType.forNumber(payloadType_);
      return result == null ? auth.PayloadType.UNRECOGNIZED : result;
    }
    /**
     * <code>.auth.PayloadType payload_type = 2;</code>
     * @param value The payloadType to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadType(auth.PayloadType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      payloadType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.auth.PayloadType payload_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayloadType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      payloadType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 3;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>bytes payload = 3;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      payload_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bytes payload = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      bitField0_ = (bitField0_ & ~0x00000004);
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }

    private int chunkIndex_ ;
    /**
     * <code>uint32 chunk_index = 4;</code>
     * @return The chunkIndex.
     */
    @java.lang.Override
    public int getChunkIndex() {
      return chunkIndex_;
    }
    /**
     * <code>uint32 chunk_index = 4;</code>
     * @param value The chunkIndex to set.
     * @return This builder for chaining.
     */
    public Builder setChunkIndex(int value) {

      chunkIndex_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 chunk_index = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearChunkIndex() {
      bitField0_ = (bitField0_ & ~0x00000008);
      chunkIndex_ = 0;
      onChanged();
      return this;
    }

    private int totalChunks_ ;
    /**
     * <code>uint32 total_chunks = 5;</code>
     * @return The totalChunks.
     */
    @java.lang.Override
    public int getTotalChunks() {
      return totalChunks_;
    }
    /**
     * <code>uint32 total_chunks = 5;</code>
     * @param value The totalChunks to set.
     * @return This builder for chaining.
     */
    public Builder setTotalChunks(int value) {

      totalChunks_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 total_chunks = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalChunks() {
      bitField0_ = (bitField0_ & ~0x00000010);
      totalChunks_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:auth.Envelope)
  }

  // @@protoc_insertion_point(class_scope:auth.Envelope)
  private static final auth.Envelope DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new auth.Envelope();
  }

  public static auth.Envelope getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Envelope>
      PARSER = new com.google.protobuf.AbstractParser<Envelope>() {
    @java.lang.Override
    public Envelope parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Envelope> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Envelope> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public auth.Envelope getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

