// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth/auth.proto
// Protobuf Java Version: 4.33.0

package auth;

@com.google.protobuf.Generated
public interface QRCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.QRCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 command_id = 1;</code>
   * @return The commandId.
   */
  long getCommandId();

  /**
   * <code>uint64 args_id = 2;</code>
   * @return The argsId.
   */
  long getArgsId();
}
