// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/auth.proto

package auth;

public interface SignalMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:auth.SignalMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.auth.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.auth.MessageType type = 1;</code>
   * @return The type.
   */
  auth.MessageType getType();

  /**
   * <pre>
   * sender ID
   * </pre>
   *
   * <code>string from = 2;</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <pre>
   * sender ID
   * </pre>
   *
   * <code>string from = 2;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <pre>
   * receiver ID (optional, for direct messages)
   * </pre>
   *
   * <code>string to = 3;</code>
   * @return The to.
   */
  java.lang.String getTo();
  /**
   * <pre>
   * receiver ID (optional, for direct messages)
   * </pre>
   *
   * <code>string to = 3;</code>
   * @return The bytes for to.
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <pre>
   * SDP offer/answer
   * </pre>
   *
   * <code>string sdp = 4;</code>
   * @return The sdp.
   */
  java.lang.String getSdp();
  /**
   * <pre>
   * SDP offer/answer
   * </pre>
   *
   * <code>string sdp = 4;</code>
   * @return The bytes for sdp.
   */
  com.google.protobuf.ByteString
      getSdpBytes();

  /**
   * <pre>
   * ICE candidate
   * </pre>
   *
   * <code>string candidate = 5;</code>
   * @return The candidate.
   */
  java.lang.String getCandidate();
  /**
   * <pre>
   * ICE candidate
   * </pre>
   *
   * <code>string candidate = 5;</code>
   * @return The bytes for candidate.
   */
  com.google.protobuf.ByteString
      getCandidateBytes();

  /**
   * <pre>
   * Room ID (optional)
   * </pre>
   *
   * <code>string room = 6;</code>
   * @return The room.
   */
  java.lang.String getRoom();
  /**
   * <pre>
   * Room ID (optional)
   * </pre>
   *
   * <code>string room = 6;</code>
   * @return The bytes for room.
   */
  com.google.protobuf.ByteString
      getRoomBytes();

  /**
   * <pre>
   * List of devices (for DEVICE_LIST response)
   * </pre>
   *
   * <code>repeated string devices = 7;</code>
   * @return A list containing the devices.
   */
  java.util.List<java.lang.String>
      getDevicesList();
  /**
   * <pre>
   * List of devices (for DEVICE_LIST response)
   * </pre>
   *
   * <code>repeated string devices = 7;</code>
   * @return The count of devices.
   */
  int getDevicesCount();
  /**
   * <pre>
   * List of devices (for DEVICE_LIST response)
   * </pre>
   *
   * <code>repeated string devices = 7;</code>
   * @param index The index of the element to return.
   * @return The devices at the given index.
   */
  java.lang.String getDevices(int index);
  /**
   * <pre>
   * List of devices (for DEVICE_LIST response)
   * </pre>
   *
   * <code>repeated string devices = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the devices at the given index.
   */
  com.google.protobuf.ByteString
      getDevicesBytes(int index);
}
