// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/auth.proto

package auth;

/**
 * <pre>
 * Generic signaling message
 * </pre>
 *
 * Protobuf type {@code auth.SignalMessage}
 */
public final class SignalMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:auth.SignalMessage)
    SignalMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SignalMessage.newBuilder() to construct.
  private SignalMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SignalMessage() {
    type_ = 0;
    from_ = "";
    to_ = "";
    sdp_ = "";
    candidate_ = "";
    room_ = "";
    devices_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SignalMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return auth.Auth.internal_static_auth_SignalMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return auth.Auth.internal_static_auth_SignalMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            auth.SignalMessage.class, auth.SignalMessage.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.auth.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.auth.MessageType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public auth.MessageType getType() {
    @SuppressWarnings("deprecation")
    auth.MessageType result = auth.MessageType.valueOf(type_);
    return result == null ? auth.MessageType.UNRECOGNIZED : result;
  }

  public static final int FROM_FIELD_NUMBER = 2;
  private volatile java.lang.Object from_;
  /**
   * <pre>
   * sender ID
   * </pre>
   *
   * <code>string from = 2;</code>
   * @return The from.
   */
  @java.lang.Override
  public java.lang.String getFrom() {
    java.lang.Object ref = from_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      from_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * sender ID
   * </pre>
   *
   * <code>string from = 2;</code>
   * @return The bytes for from.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromBytes() {
    java.lang.Object ref = from_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      from_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_FIELD_NUMBER = 3;
  private volatile java.lang.Object to_;
  /**
   * <pre>
   * receiver ID (optional, for direct messages)
   * </pre>
   *
   * <code>string to = 3;</code>
   * @return The to.
   */
  @java.lang.Override
  public java.lang.String getTo() {
    java.lang.Object ref = to_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      to_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * receiver ID (optional, for direct messages)
   * </pre>
   *
   * <code>string to = 3;</code>
   * @return The bytes for to.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToBytes() {
    java.lang.Object ref = to_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      to_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SDP_FIELD_NUMBER = 4;
  private volatile java.lang.Object sdp_;
  /**
   * <pre>
   * SDP offer/answer
   * </pre>
   *
   * <code>string sdp = 4;</code>
   * @return The sdp.
   */
  @java.lang.Override
  public java.lang.String getSdp() {
    java.lang.Object ref = sdp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sdp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * SDP offer/answer
   * </pre>
   *
   * <code>string sdp = 4;</code>
   * @return The bytes for sdp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSdpBytes() {
    java.lang.Object ref = sdp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sdp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CANDIDATE_FIELD_NUMBER = 5;
  private volatile java.lang.Object candidate_;
  /**
   * <pre>
   * ICE candidate
   * </pre>
   *
   * <code>string candidate = 5;</code>
   * @return The candidate.
   */
  @java.lang.Override
  public java.lang.String getCandidate() {
    java.lang.Object ref = candidate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      candidate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ICE candidate
   * </pre>
   *
   * <code>string candidate = 5;</code>
   * @return The bytes for candidate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCandidateBytes() {
    java.lang.Object ref = candidate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      candidate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOM_FIELD_NUMBER = 6;
  private volatile java.lang.Object room_;
  /**
   * <pre>
   * Room ID (optional)
   * </pre>
   *
   * <code>string room = 6;</code>
   * @return The room.
   */
  @java.lang.Override
  public java.lang.String getRoom() {
    java.lang.Object ref = room_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      room_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Room ID (optional)
   * </pre>
   *
   * <code>string room = 6;</code>
   * @return The bytes for room.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoomBytes() {
    java.lang.Object ref = room_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      room_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICES_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList devices_;
  /**
   * <pre>
   * List of devices (for DEVICE_LIST response)
   * </pre>
   *
   * <code>repeated string devices = 7;</code>
   * @return A list containing the devices.
   */
  public com.google.protobuf.ProtocolStringList
      getDevicesList() {
    return devices_;
  }
  /**
   * <pre>
   * List of devices (for DEVICE_LIST response)
   * </pre>
   *
   * <code>repeated string devices = 7;</code>
   * @return The count of devices.
   */
  public int getDevicesCount() {
    return devices_.size();
  }
  /**
   * <pre>
   * List of devices (for DEVICE_LIST response)
   * </pre>
   *
   * <code>repeated string devices = 7;</code>
   * @param index The index of the element to return.
   * @return The devices at the given index.
   */
  public java.lang.String getDevices(int index) {
    return devices_.get(index);
  }
  /**
   * <pre>
   * List of devices (for DEVICE_LIST response)
   * </pre>
   *
   * <code>repeated string devices = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the devices at the given index.
   */
  public com.google.protobuf.ByteString
      getDevicesBytes(int index) {
    return devices_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != auth.MessageType.UNKNOWN.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(from_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, from_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(to_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sdp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sdp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(candidate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, candidate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(room_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, room_);
    }
    for (int i = 0; i < devices_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, devices_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != auth.MessageType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(from_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, from_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(to_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, to_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sdp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sdp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(candidate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, candidate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(room_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, room_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < devices_.size(); i++) {
        dataSize += computeStringSizeNoTag(devices_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDevicesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof auth.SignalMessage)) {
      return super.equals(obj);
    }
    auth.SignalMessage other = (auth.SignalMessage) obj;

    if (type_ != other.type_) return false;
    if (!getFrom()
        .equals(other.getFrom())) return false;
    if (!getTo()
        .equals(other.getTo())) return false;
    if (!getSdp()
        .equals(other.getSdp())) return false;
    if (!getCandidate()
        .equals(other.getCandidate())) return false;
    if (!getRoom()
        .equals(other.getRoom())) return false;
    if (!getDevicesList()
        .equals(other.getDevicesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + getFrom().hashCode();
    hash = (37 * hash) + TO_FIELD_NUMBER;
    hash = (53 * hash) + getTo().hashCode();
    hash = (37 * hash) + SDP_FIELD_NUMBER;
    hash = (53 * hash) + getSdp().hashCode();
    hash = (37 * hash) + CANDIDATE_FIELD_NUMBER;
    hash = (53 * hash) + getCandidate().hashCode();
    hash = (37 * hash) + ROOM_FIELD_NUMBER;
    hash = (53 * hash) + getRoom().hashCode();
    if (getDevicesCount() > 0) {
      hash = (37 * hash) + DEVICES_FIELD_NUMBER;
      hash = (53 * hash) + getDevicesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static auth.SignalMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static auth.SignalMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static auth.SignalMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static auth.SignalMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static auth.SignalMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static auth.SignalMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static auth.SignalMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static auth.SignalMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static auth.SignalMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static auth.SignalMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static auth.SignalMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static auth.SignalMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(auth.SignalMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Generic signaling message
   * </pre>
   *
   * Protobuf type {@code auth.SignalMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:auth.SignalMessage)
      auth.SignalMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return auth.Auth.internal_static_auth_SignalMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return auth.Auth.internal_static_auth_SignalMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              auth.SignalMessage.class, auth.SignalMessage.Builder.class);
    }

    // Construct using auth.SignalMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      from_ = "";

      to_ = "";

      sdp_ = "";

      candidate_ = "";

      room_ = "";

      devices_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return auth.Auth.internal_static_auth_SignalMessage_descriptor;
    }

    @java.lang.Override
    public auth.SignalMessage getDefaultInstanceForType() {
      return auth.SignalMessage.getDefaultInstance();
    }

    @java.lang.Override
    public auth.SignalMessage build() {
      auth.SignalMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public auth.SignalMessage buildPartial() {
      auth.SignalMessage result = new auth.SignalMessage(this);
      int from_bitField0_ = bitField0_;
      result.type_ = type_;
      result.from_ = from_;
      result.to_ = to_;
      result.sdp_ = sdp_;
      result.candidate_ = candidate_;
      result.room_ = room_;
      if (((bitField0_ & 0x00000001) != 0)) {
        devices_ = devices_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.devices_ = devices_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof auth.SignalMessage) {
        return mergeFrom((auth.SignalMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(auth.SignalMessage other) {
      if (other == auth.SignalMessage.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getFrom().isEmpty()) {
        from_ = other.from_;
        onChanged();
      }
      if (!other.getTo().isEmpty()) {
        to_ = other.to_;
        onChanged();
      }
      if (!other.getSdp().isEmpty()) {
        sdp_ = other.sdp_;
        onChanged();
      }
      if (!other.getCandidate().isEmpty()) {
        candidate_ = other.candidate_;
        onChanged();
      }
      if (!other.getRoom().isEmpty()) {
        room_ = other.room_;
        onChanged();
      }
      if (!other.devices_.isEmpty()) {
        if (devices_.isEmpty()) {
          devices_ = other.devices_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureDevicesIsMutable();
          devices_.addAll(other.devices_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();

              break;
            } // case 8
            case 18: {
              from_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              to_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              sdp_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              candidate_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              room_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureDevicesIsMutable();
              devices_.add(s);
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.auth.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.auth.MessageType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.auth.MessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public auth.MessageType getType() {
      @SuppressWarnings("deprecation")
      auth.MessageType result = auth.MessageType.valueOf(type_);
      return result == null ? auth.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.auth.MessageType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(auth.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.auth.MessageType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object from_ = "";
    /**
     * <pre>
     * sender ID
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The from.
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * sender ID
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The bytes for from.
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * sender ID
     * </pre>
     *
     * <code>string from = 2;</code>
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setFrom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      from_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sender ID
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrom() {
      
      from_ = getDefaultInstance().getFrom();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * sender ID
     * </pre>
     *
     * <code>string from = 2;</code>
     * @param value The bytes for from to set.
     * @return This builder for chaining.
     */
    public Builder setFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      from_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object to_ = "";
    /**
     * <pre>
     * receiver ID (optional, for direct messages)
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The to.
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * receiver ID (optional, for direct messages)
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The bytes for to.
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * receiver ID (optional, for direct messages)
     * </pre>
     *
     * <code>string to = 3;</code>
     * @param value The to to set.
     * @return This builder for chaining.
     */
    public Builder setTo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      to_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * receiver ID (optional, for direct messages)
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTo() {
      
      to_ = getDefaultInstance().getTo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * receiver ID (optional, for direct messages)
     * </pre>
     *
     * <code>string to = 3;</code>
     * @param value The bytes for to to set.
     * @return This builder for chaining.
     */
    public Builder setToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      to_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sdp_ = "";
    /**
     * <pre>
     * SDP offer/answer
     * </pre>
     *
     * <code>string sdp = 4;</code>
     * @return The sdp.
     */
    public java.lang.String getSdp() {
      java.lang.Object ref = sdp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sdp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * SDP offer/answer
     * </pre>
     *
     * <code>string sdp = 4;</code>
     * @return The bytes for sdp.
     */
    public com.google.protobuf.ByteString
        getSdpBytes() {
      java.lang.Object ref = sdp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * SDP offer/answer
     * </pre>
     *
     * <code>string sdp = 4;</code>
     * @param value The sdp to set.
     * @return This builder for chaining.
     */
    public Builder setSdp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sdp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SDP offer/answer
     * </pre>
     *
     * <code>string sdp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSdp() {
      
      sdp_ = getDefaultInstance().getSdp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SDP offer/answer
     * </pre>
     *
     * <code>string sdp = 4;</code>
     * @param value The bytes for sdp to set.
     * @return This builder for chaining.
     */
    public Builder setSdpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sdp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object candidate_ = "";
    /**
     * <pre>
     * ICE candidate
     * </pre>
     *
     * <code>string candidate = 5;</code>
     * @return The candidate.
     */
    public java.lang.String getCandidate() {
      java.lang.Object ref = candidate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ICE candidate
     * </pre>
     *
     * <code>string candidate = 5;</code>
     * @return The bytes for candidate.
     */
    public com.google.protobuf.ByteString
        getCandidateBytes() {
      java.lang.Object ref = candidate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ICE candidate
     * </pre>
     *
     * <code>string candidate = 5;</code>
     * @param value The candidate to set.
     * @return This builder for chaining.
     */
    public Builder setCandidate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      candidate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ICE candidate
     * </pre>
     *
     * <code>string candidate = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidate() {
      
      candidate_ = getDefaultInstance().getCandidate();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ICE candidate
     * </pre>
     *
     * <code>string candidate = 5;</code>
     * @param value The bytes for candidate to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      candidate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object room_ = "";
    /**
     * <pre>
     * Room ID (optional)
     * </pre>
     *
     * <code>string room = 6;</code>
     * @return The room.
     */
    public java.lang.String getRoom() {
      java.lang.Object ref = room_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        room_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Room ID (optional)
     * </pre>
     *
     * <code>string room = 6;</code>
     * @return The bytes for room.
     */
    public com.google.protobuf.ByteString
        getRoomBytes() {
      java.lang.Object ref = room_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        room_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Room ID (optional)
     * </pre>
     *
     * <code>string room = 6;</code>
     * @param value The room to set.
     * @return This builder for chaining.
     */
    public Builder setRoom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      room_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Room ID (optional)
     * </pre>
     *
     * <code>string room = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoom() {
      
      room_ = getDefaultInstance().getRoom();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Room ID (optional)
     * </pre>
     *
     * <code>string room = 6;</code>
     * @param value The bytes for room to set.
     * @return This builder for chaining.
     */
    public Builder setRoomBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      room_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList devices_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDevicesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        devices_ = new com.google.protobuf.LazyStringArrayList(devices_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * List of devices (for DEVICE_LIST response)
     * </pre>
     *
     * <code>repeated string devices = 7;</code>
     * @return A list containing the devices.
     */
    public com.google.protobuf.ProtocolStringList
        getDevicesList() {
      return devices_.getUnmodifiableView();
    }
    /**
     * <pre>
     * List of devices (for DEVICE_LIST response)
     * </pre>
     *
     * <code>repeated string devices = 7;</code>
     * @return The count of devices.
     */
    public int getDevicesCount() {
      return devices_.size();
    }
    /**
     * <pre>
     * List of devices (for DEVICE_LIST response)
     * </pre>
     *
     * <code>repeated string devices = 7;</code>
     * @param index The index of the element to return.
     * @return The devices at the given index.
     */
    public java.lang.String getDevices(int index) {
      return devices_.get(index);
    }
    /**
     * <pre>
     * List of devices (for DEVICE_LIST response)
     * </pre>
     *
     * <code>repeated string devices = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the devices at the given index.
     */
    public com.google.protobuf.ByteString
        getDevicesBytes(int index) {
      return devices_.getByteString(index);
    }
    /**
     * <pre>
     * List of devices (for DEVICE_LIST response)
     * </pre>
     *
     * <code>repeated string devices = 7;</code>
     * @param index The index to set the value at.
     * @param value The devices to set.
     * @return This builder for chaining.
     */
    public Builder setDevices(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDevicesIsMutable();
      devices_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of devices (for DEVICE_LIST response)
     * </pre>
     *
     * <code>repeated string devices = 7;</code>
     * @param value The devices to add.
     * @return This builder for chaining.
     */
    public Builder addDevices(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDevicesIsMutable();
      devices_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of devices (for DEVICE_LIST response)
     * </pre>
     *
     * <code>repeated string devices = 7;</code>
     * @param values The devices to add.
     * @return This builder for chaining.
     */
    public Builder addAllDevices(
        java.lang.Iterable<java.lang.String> values) {
      ensureDevicesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, devices_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of devices (for DEVICE_LIST response)
     * </pre>
     *
     * <code>repeated string devices = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDevices() {
      devices_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List of devices (for DEVICE_LIST response)
     * </pre>
     *
     * <code>repeated string devices = 7;</code>
     * @param value The bytes of the devices to add.
     * @return This builder for chaining.
     */
    public Builder addDevicesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureDevicesIsMutable();
      devices_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:auth.SignalMessage)
  }

  // @@protoc_insertion_point(class_scope:auth.SignalMessage)
  private static final auth.SignalMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new auth.SignalMessage();
  }

  public static auth.SignalMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SignalMessage>
      PARSER = new com.google.protobuf.AbstractParser<SignalMessage>() {
    @java.lang.Override
    public SignalMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SignalMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SignalMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public auth.SignalMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

